In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/asaniczka/amazon-uk-products-dataset-2023/amz_uk_processed_data.csv

In [2]:
df = pd.read_csv('/kaggle/input/datasets/asaniczka/amazon-uk-products-dataset-2023/amz_uk_processed_data.csv')

In [3]:
df.head()

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
0,B09B96TG33,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/71C3lbbeLs...,https://www.amazon.co.uk/dp/B09B96TG33,4.7,15308,21.99,False,0,Hi-Fi Speakers
1,B01HTH3C8S,"Anker Soundcore mini, Super-Portable Bluetooth...",https://m.media-amazon.com/images/I/61c5rSxwP0...,https://www.amazon.co.uk/dp/B01HTH3C8S,4.7,98099,23.99,True,0,Hi-Fi Speakers
2,B09B8YWXDF,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/61j3SEUjMJ...,https://www.amazon.co.uk/dp/B09B8YWXDF,4.7,15308,21.99,False,0,Hi-Fi Speakers
3,B09B8T5VGV,"Echo Dot with clock (5th generation, 2022 rele...",https://m.media-amazon.com/images/I/71yf6yTNWS...,https://www.amazon.co.uk/dp/B09B8T5VGV,4.7,7205,31.99,False,0,Hi-Fi Speakers
4,B09WX6QD65,Introducing Echo Pop | Full sound compact Wi-F...,https://m.media-amazon.com/images/I/613dEoF9-r...,https://www.amazon.co.uk/dp/B09WX6QD65,4.6,1881,17.99,False,0,Hi-Fi Speakers

In [4]:
df.shape

(2222742, 10)

In [5]:
df.tail()

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
2222737,B0CHSD7P2Q,"Motorbike Armour, Motorbike Clothing, Cycling ...",https://m.media-amazon.com/images/I/61ycPU7k4k...,https://www.amazon.co.uk/dp/B0CHSD7P2Q,0.0,0,22.34,False,0,Motorbike Clothing
2222738,B0B7B8FNBQ,PROFIRST Waterproof Motorcycle 2 Piece Ladies ...,https://m.media-amazon.com/images/I/51gkh0iYT5...,https://www.amazon.co.uk/dp/B0B7B8FNBQ,0.0,0,97.99,False,0,Motorbike Clothing
2222739,B0BD5FL5FB,Men’s Motorcycle Motorbike Biker Trousers Kevl...,https://m.media-amazon.com/images/I/81gJgaMHg4...,https://www.amazon.co.uk/dp/B0BD5FL5FB,0.0,0,52.99,False,0,Motorbike Clothing
2222740,B008OYLL4I,Texpeed Mens Motorcycle Motorbike Biker Trouse...,https://m.media-amazon.com/images/I/81KQ5askGG...,https://www.amazon.co.uk/dp/B008OYLL4I,4.3,404,79.99,False,0,Motorbike Clothing
2222741,B08P3W9B3T,RIDEX CJ223 Motorcycle Motorbike Jacket Armour...,https://m.media-amazon.com/images/I/61QaDygK8m...,https://www.amazon.co.uk/dp/B08P3W9B3T,4.5,34,53.99,False,0,Motorbike Clothing

In [6]:
df.sample(2)

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
1301661,B0CKH9SDYB,Halloween Countdown Advent Calendar - Wooden C...,https://m.media-amazon.com/images/I/71JGy88c7Q...,https://www.amazon.co.uk/dp/B0CKH9SDYB,0.0,0,10.78,False,0,Toy Advent Calendars
931897,B0CGDB7KVW,Baiomawzh Women's Fleece Jacket with Hood Long...,https://m.media-amazon.com/images/I/71tk33lKIW...,https://www.amazon.co.uk/dp/B0CGDB7KVW,0.0,0,17.98,False,0,Sports & Outdoors

In [7]:
df.isna().sum()

asin                 0
title                0
imgUrl               0
productURL           0
stars                0
reviews              0
price                0
isBestSeller         0
boughtInLastMonth    0
categoryName         0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2222742 entries, 0 to 2222741
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   asin               object
 1   title              object
 2   imgUrl             object
 3   productURL         object
 4   stars              float64
 5   reviews            int64
 6   price              float64
 7   isBestSeller       bool
 8   boughtInLastMonth  int64
 9   categoryName       object
dtypes: bool(1), float64(2), int64(2), object(5)
memory usage: 154.7+ MB

In [9]:
df.describe()

              stars       reviews         price  boughtInLastMonth
count  2.222742e+06  2.222742e+06  2.222742e+06       2.222742e+06
mean   2.031870e+00  3.821617e+02  9.425737e+01       1.856902e+01
std    2.185497e+00  5.020752e+03  3.606225e+02       1.919030e+02
min    0.000000e+00  0.000000e+00  0.000000e+00       0.000000e+00
25%    0.000000e+00  0.000000e+00  1.000000e+01       0.000000e+00
50%    0.000000e+00  0.000000e+00  1.990000e+01       0.000000e+00
75%    4.400000e+00  4.400000e+01  4.771000e+01       0.000000e+00
max    5.000000e+00  1.356658e+06  1.000000e+05       5.000000e+04

In [10]:
df.corr(numeric_only = True)

,stars,reviews,price,isBestSeller,boughtInLastMonth
stars,1.000000,0.085124,-0.122505,0.056826,0.106259
reviews,0.085124,1.000000,-0.012482,0.061835,0.095229
price,-0.122505,-0.012482,1.000000,-0.010241,-0.021390
isBestSeller,0.056826,0.061835,-0.010241,1.000000,0.222299
boughtInLastMonth,0.106259,0.095229,-0.021390,0.222299,1.000000

In [11]:
df['isBestSeller']

0          False
1           True
2          False
3          False
4          False
           ...
2222737    False
2222738    False
2222739    False
2222740    False
2222741    False
Name: isBestSeller, Length: 2222742, dtype: bool

In [12]:
num_cols = df.select_dtypes(include='number')

In [13]:
cat_cols = df.select_dtypes(exclude = 'number')

In [14]:
num_cols

         stars  reviews  price  boughtInLastMonth
0          4.7    15308  21.99                  0
1          4.7    98099  23.99                  0
2          4.7    15308  21.99                  0
3          4.7     7205  31.99                  0
4          4.6     1881  17.99                  0
...        ...      ...    ...                ...
2222737    0.0        0  22.34                  0
2222738    0.0        0  97.99                  0
2222739    0.0        0  52.99                  0
2222740    4.3      404  79.99                  0
2222741    4.5       34  53.99                  0

[2222742 rows x 4 columns]

In [15]:
cat_cols

,asin,title,imgUrl,productURL,isBestSeller,categoryName
0,B09B96TG33,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/71C3lbbeLs...,https://www.amazon.co.uk/dp/B09B96TG33,False,Hi-Fi Speakers
1,B01HTH3C8S,"Anker Soundcore mini, Super-Portable Bluetooth...",https://m.media-amazon.com/images/I/61c5rSxwP0...,https://www.amazon.co.uk/dp/B01HTH3C8S,True,Hi-Fi Speakers
2,B09B8YWXDF,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/61j3SEUjMJ...,https://www.amazon.co.uk/dp/B09B8YWXDF,False,Hi-Fi Speakers
3,B09B8T5VGV,"Echo Dot with clock (5th generation, 2022 rele...",https://m.media-amazon.com/images/I/71yf6yTNWS...,https://www.amazon.co.uk/dp/B09B8T5VGV,False,Hi-Fi Speakers
4,B09WX6QD65,Introducing Echo Pop | Full sound compact Wi-F...,https://m.media-amazon.com/images/I/613dEoF9-r...,https://www.amazon.co.uk/dp/B09WX6QD65,False,Hi-Fi Speakers
...,...,...,...,...,...,...
2222737,B0CHSD7P2Q,"Motorbike Armour, Motorbike Clothing, Cycling ...",https://m.media-amazon.com/images/I/61ycPU7k4k...,https://www.amazon.co.uk/dp/B0CHSD7P2Q,False,Motorbike Clothing
2222738,B0B7B8FNBQ,PROFIRST Waterproof Motorcycle 2 Piece Ladies ...,https://m.media-amazon.com/images/I/51gkh0iYT5...,https://www.amazon.co.uk/dp/B0B7B8FNBQ,False,Motorbike Clothing
2222739,B0BD5FL5FB,Men’s Motorcycle Motorbike Biker Trousers Kevl...,https://m.media-amazon.com/images/I/81gJgaMHg4...,https://www.amazon.co.uk/dp/B0BD5FL5FB,False,Motorbike Clothing
2222740,B008OYLL4I,Texpeed Mens Motorcycle Motorbike Biker Trouse...,https://m.media-amazon.com/images/I/81KQ5askGG...,https://www.amazon.co.uk/dp/B008OYLL4I,False,Motorbike Clothing
2222741,B08P3W9B3T,RIDEX CJ223 Motorcycle Motorbike Jacket Armour...,https://m.media-amazon.com/images/I/61QaDygK8m...,https://www.amazon.co.uk/dp/B08P3W9B3T,False,Motorbike Clothing

In [16]:
df['imgUrl']

0          https://m.media-amazon.com/images/I/71C3lbbeLs...
1          https://m.media-amazon.com/images/I/61c5rSxwP0...
2          https://m.media-amazon.com/images/I/61j3SEUjMJ...
3          https://m.media-amazon.com/images/I/71yf6yTNWS...
4          https://m.media-amazon.com/images/I/613dEoF9-r...
                                 ...
2222737    https://m.media-amazon.com/images/I/61ycPU7k4k...
2222738    https://m.media-amazon.com/images/I/51gkh0iYT5...
2222739    https://m.media-amazon.com/images/I/81gJgaMHg4...
2222740    https://m.media-amazon.com/images/I/81KQ5askGG...
2222741    https://m.media-amazon.com/images/I/61QaDygK8m...
Name: imgUrl, Length: 2222742, dtype: object

In [17]:
df.shape

(2222742, 10)

In [18]:
df.columns

Index(['asin', 'title', 'imgUrl', 'productURL', 'stars', 'reviews', 'price',
       'isBestSeller', 'boughtInLastMonth', 'categoryName'],
      dtype='object')

In [19]:
num_cols.columns

Index(['stars', 'reviews', 'price', 'boughtInLastMonth'], dtype='object')

In [20]:
cat_cols.columns

Index(['asin', 'title', 'imgUrl', 'productURL', 'isBestSeller',
       'categoryName'],
      dtype='object')

In [21]:
num_cols['price']

0          21.99
1          23.99
2          21.99
3          31.99
4          17.99
           ...
2222737    22.34
2222738    97.99
2222739    52.99
2222740    79.99
2222741    53.99
Name: price, Length: 2222742, dtype: float64

In [22]:
#Converting Pounds Into Rupees
df['price'] = df['price'] * 127.43

In [23]:
df['price']

0           2802.1857
1           3057.0457
2           2802.1857
3           4076.4857
4           2292.4657
              ...
2222737     2846.7862
2222738    12486.8657
2222739     6752.5157
2222740    10193.1257
2222741     6879.9457
Name: price, Length: 2222742, dtype: float64

In [24]:
df['price'] = df['price'].apply(
    lambda x: np.ceil(x) if x % 1 >= 0.5 else np.floor(x)
)

In [25]:
df['price']

0           2802.0
1           3057.0
2           2802.0
3           4076.0
4           2292.0
            ...
2222737     2847.0
2222738    12487.0
2222739     6753.0
2222740    10193.0
2222741     6880.0
Name: price, Length: 2222742, dtype: float64

In [26]:
df['productURL']

0          https://www.amazon.co.uk/dp/B09B96TG33
1          https://www.amazon.co.uk/dp/B01HTH3C8S
2          https://www.amazon.co.uk/dp/B09B8YWXDF
3          https://www.amazon.co.uk/dp/B09B8T5VGV
4          https://www.amazon.co.uk/dp/B09WX6QD65
                            ...
2222737    https://www.amazon.co.uk/dp/B0CHSD7P2Q
2222738    https://www.amazon.co.uk/dp/B0B7B8FNBQ
2222739    https://www.amazon.co.uk/dp/B0BD5FL5FB
2222740    https://www.amazon.co.uk/dp/B008OYLL4I
2222741    https://www.amazon.co.uk/dp/B08P3W9B3T
Name: productURL, Length: 2222742, dtype: object

In [27]:
df.sample(2)

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
1055027,B09NYG2FP2,BritishBasics Quick Thaw Fridge/Freezer Deicer...,https://m.media-amazon.com/images/I/618XDscoYt...,https://www.amazon.co.uk/dp/B09NYG2FP2,3.8,79,879.0,False,50,Large Appliances
1982460,B07ZJF4WTP,Yellow Awareness Ribbon Pin Badge For Sarcoma ...,https://m.media-amazon.com/images/I/516CbFQxjj...,https://www.amazon.co.uk/dp/B07ZJF4WTP,4.7,6,827.0,False,0,Handmade Jewellery

In [28]:
df['categoryName'].value_counts()

categoryName
Sports & Outdoors                 826076
Skin Care                          18755
Fragrances                         18563
Make-up                            18453
Manicure & Pedicure Products       17212
                                   ...
Torches                               64
Smart Home Security & Lighting        57
Lighting                              50
Smart Speakers                        25
Cameras                               12
Name: count, Length: 296, dtype: int64

In [29]:
df.drop(columns = ['imgUrl','productURL','title'],axis = 1,inplace = True)

In [30]:
df.sample(5)

,asin,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
188666,B0CHPP9GVC,0.0,0,2693.0,False,0,Computer Printers
1348713,B08YFDP8X1,3.9,32,2003.0,False,0,Sports & Outdoors
2120057,B07SCTMPR3,4.0,99,1248.0,False,0,Car & Vehicle Electronics
1053349,B09YRBYDZY,4.5,2,1218.0,False,0,Vacuums & Floorcare
170044,B0848SMPTM,3.6,16,1973.0,False,0,Fragrances

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,LabelEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [32]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,roc_curve,roc_auc_score

In [33]:
df.drop(columns = ['asin'],axis = 1,inplace = True)

In [34]:
X = df.drop(columns = ['isBestSeller'],axis = 1)

In [35]:
df['isBestSeller'] = df['isBestSeller'].apply(lambda x: 1 if x else 0)

In [36]:
y = df['isBestSeller']

In [63]:
df['isBestSeller'].value_counts()

isBestSeller
0    2216724
1       6018
Name: count, dtype: int64

In [37]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [38]:
X_train.shape

(1778193, 5)

In [39]:
X_test.shape

(444549, 5)

In [40]:
y_train.shape

(1778193,)

In [41]:
y_test.shape

(444549,)

In [42]:
X_train

,stars,reviews,price,boughtInLastMonth,categoryName
757021,4.6,126,28140.0,0,Sports & Outdoors
1953809,0.0,0,751.0,0,Sports & Outdoors
1305660,0.0,0,2086.0,0,Toy Advent Calendars
1440599,0.0,0,1451.0,0,Sports & Outdoors
1809750,5.0,1,858.0,0,Remote & App-Controlled Devices
...,...,...,...,...,...
1570006,4.7,308,12103.0,0,Camera & Photo Accessories
732180,0.0,0,48296.0,0,Sports & Outdoors
110268,5.0,4,1911.0,0,Handmade Gifts
1692743,0.0,0,28083.0,0,Sports & Outdoors
2219110,0.0,0,2306.0,0,Table Tennis

In [43]:
tr1 = ColumnTransformer(transformers=[
    (
        'OneHotEncoding',
        OneHotEncoder(
            sparse_output=True,
            handle_unknown='ignore'
        ),
        ['categoryName']
    ),
    (
        'StandardScaling',
        StandardScaler(),
        ['stars', 'reviews', 'price', 'boughtInLastMonth']
    )
])

In [44]:
tr1

ColumnTransformer(transformers=[('OneHotEncoding',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['categoryName']),
                                ('StandardScaling', StandardScaler(),
                                 ['stars', 'reviews', 'price',
                                  'boughtInLastMonth'])])

In [45]:
pipe1 = Pipeline(steps=[
    ('preprocessing', tr1),
    ('model', RandomForestClassifier(
        n_estimators=100,
        max_depth=15,
        min_samples_split=10,
        min_samples_leaf=4,
        max_features='sqrt',
        max_leaf_nodes=100,
        min_impurity_decrease=0.01,
        bootstrap=True,
        max_samples=0.8,
        class_weight='balanced',
        random_state=42,
        n_jobs=-1,
        warm_start=True
    ))
])

In [ ]:
# # 30K
# X_batch = X_train.iloc[:30_000]
# y_batch = y_train.iloc[:30_000]

# pipe1.fit(X_batch, y_batch)

In [47]:
X_fit = X_train.iloc[:30_000]

tr1.fit(X_fit)

print("✅ Preprocessor fitted successfully")

del X_fit

import gc
gc.collect()

✅ Preprocessor fitted successfully

23

In [48]:
X_test_batch = X_train.iloc[:100]

X_test_transformed = tr1.transform(X_test_batch)

print("✅ Transform successful")
print("Shape:", X_test_transformed.shape)

del X_test_batch, X_test_transformed
gc.collect()

✅ Transform successful
Shape: (100, 294)

23

In [49]:
model = RandomForestClassifier(
    n_estimators=10,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=4,
    max_features='sqrt',
    max_leaf_nodes=100,
    min_impurity_decrease=0.01,
    bootstrap=True,
    max_samples=0.8,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    warm_start=True
)

batch_size = 30_000
trees_per_batch = 5

for start in range(0, len(X_train), batch_size):

    end = min(start + batch_size, len(X_train))

    print(f"\nProcessing rows {start:,} → {end:,}")

    X_batch = X_train.iloc[start:end]
    y_batch = y_train.iloc[start:end]

    X_batch_transformed = tr1.transform(X_batch)

    model.n_estimators += trees_per_batch

    model.fit(X_batch_transformed, y_batch)

    print(f"✅ Completed | Trees: {model.n_estimators}")

    del X_batch
    del y_batch
    del X_batch_transformed

    gc.collect()

Processing rows 0 → 30,000
✅ Completed | Trees: 15

Processing rows 30,000 → 60,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 20

Processing rows 60,000 → 90,000
✅ Completed | Trees: 25

Processing rows 90,000 → 120,000
✅ Completed | Trees: 30

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 120,000 → 150,000
✅ Completed | Trees: 35

Processing rows 150,000 → 180,000
✅ Completed | Trees: 40

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 180,000 → 210,000
✅ Completed | Trees: 45

Processing rows 210,000 → 240,000
✅ Completed | Trees: 50

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 240,000 → 270,000
✅ Completed | Trees: 55

Processing rows 270,000 → 300,000
✅ Completed | Trees: 60

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 300,000 → 330,000
✅ Completed | Trees: 65

Processing rows 330,000 → 360,000
✅ Completed | Trees: 70

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 360,000 → 390,000
✅ Completed | Trees: 75

Processing rows 390,000 → 420,000
✅ Completed | Trees: 80

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 420,000 → 450,000
✅ Completed | Trees: 85

Processing rows 450,000 → 480,000
✅ Completed | Trees: 90

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 480,000 → 510,000
✅ Completed | Trees: 95

Processing rows 510,000 → 540,000
✅ Completed | Trees: 100

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 540,000 → 570,000
✅ Completed | Trees: 105

Processing rows 570,000 → 600,000
✅ Completed | Trees: 110

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 600,000 → 630,000
✅ Completed | Trees: 115

Processing rows 630,000 → 660,000
✅ Completed | Trees: 120

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 660,000 → 690,000
✅ Completed | Trees: 125

Processing rows 690,000 → 720,000
✅ Completed | Trees: 130

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 720,000 → 750,000
✅ Completed | Trees: 135

Processing rows 750,000 → 780,000
✅ Completed | Trees: 140

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 780,000 → 810,000
✅ Completed | Trees: 145

Processing rows 810,000 → 840,000
✅ Completed | Trees: 150

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 840,000 → 870,000
✅ Completed | Trees: 155

Processing rows 870,000 → 900,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 160

Processing rows 900,000 → 930,000
✅ Completed | Trees: 165

Processing rows 930,000 → 960,000
✅ Completed | Trees: 170

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 960,000 → 990,000
✅ Completed | Trees: 175

Processing rows 990,000 → 1,020,000
✅ Completed | Trees: 180

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,020,000 → 1,050,000
✅ Completed | Trees: 185

Processing rows 1,050,000 → 1,080,000
✅ Completed | Trees: 190

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,080,000 → 1,110,000
✅ Completed | Trees: 195

Processing rows 1,110,000 → 1,140,000
✅ Completed | Trees: 200

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,140,000 → 1,170,000
✅ Completed | Trees: 205

Processing rows 1,170,000 → 1,200,000
✅ Completed | Trees: 210

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,200,000 → 1,230,000
✅ Completed | Trees: 215

Processing rows 1,230,000 → 1,260,000
✅ Completed | Trees: 220

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,260,000 → 1,290,000
✅ Completed | Trees: 225

Processing rows 1,290,000 → 1,320,000
✅ Completed | Trees: 230

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,320,000 → 1,350,000
✅ Completed | Trees: 235

Processing rows 1,350,000 → 1,380,000
✅ Completed | Trees: 240

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,380,000 → 1,410,000
✅ Completed | Trees: 245

Processing rows 1,410,000 → 1,440,000
✅ Completed | Trees: 250

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,440,000 → 1,470,000
✅ Completed | Trees: 255

Processing rows 1,470,000 → 1,500,000
✅ Completed | Trees: 260

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,500,000 → 1,530,000
✅ Completed | Trees: 265

Processing rows 1,530,000 → 1,560,000
✅ Completed | Trees: 270

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,560,000 → 1,590,000
✅ Completed | Trees: 275

Processing rows 1,590,000 → 1,620,000
✅ Completed | Trees: 280

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,620,000 → 1,650,000
✅ Completed | Trees: 285

Processing rows 1,650,000 → 1,680,000
✅ Completed | Trees: 290

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,680,000 → 1,710,000
✅ Completed | Trees: 295

Processing rows 1,710,000 → 1,740,000
✅ Completed | Trees: 300

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,740,000 → 1,770,000
✅ Completed | Trees: 305

Processing rows 1,770,000 → 1,778,193
✅ Completed | Trees: 310

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

In [50]:
X_test_transformed = tr1.transform(X_test)
y_pred = model.predict(X_test_transformed)

In [51]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8311277272021756
              precision    recall  f1-score   support

           0       1.00      0.83      0.91    443358
           1       0.01      0.90      0.03      1191

    accuracy                           0.83    444549
   macro avg       0.51      0.86      0.47    444549
weighted avg       1.00      0.83      0.91    444549

In [52]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[368409  74949]
 [   123   1068]]

In [53]:
model = RandomForestClassifier(
    n_estimators=5,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=4,
    max_features='sqrt',
    max_leaf_nodes=100,
    min_impurity_decrease=0.01,
    bootstrap=True,
    max_samples=0.8,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    warm_start=True
)

batch_size = 30_000
trees_per_batch = 5

for start in range(0, len(X_train), batch_size):

    end = min(start + batch_size, len(X_train))

    print(f"\nProcessing rows {start:,} → {end:,}")

    # Get batch
    X_batch = X_train.iloc[start:end]
    y_batch = y_train.iloc[start:end]

    # Transform batch
    X_batch_transformed = tr1.transform(X_batch)

    # Add new trees
    if start != 0:
        model.n_estimators += trees_per_batch

    # Train
    model.fit(
        X_batch_transformed,
        y_batch
    )

    print(f"✅ Completed | Trees: {model.n_estimators}")

    # Free memory
    del X_batch
    del y_batch
    del X_batch_transformed

    gc.collect()

Processing rows 0 → 30,000
✅ Completed | Trees: 5

Processing rows 30,000 → 60,000
✅ Completed | Trees: 10

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 60,000 → 90,000
✅ Completed | Trees: 15

Processing rows 90,000 → 120,000
✅ Completed | Trees: 20

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 120,000 → 150,000
✅ Completed | Trees: 25

Processing rows 150,000 → 180,000
✅ Completed | Trees: 30

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 180,000 → 210,000
✅ Completed | Trees: 35

Processing rows 210,000 → 240,000
✅ Completed | Trees: 40

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 240,000 → 270,000
✅ Completed | Trees: 45

Processing rows 270,000 → 300,000
✅ Completed | Trees: 50

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 300,000 → 330,000
✅ Completed | Trees: 55

Processing rows 330,000 → 360,000
✅ Completed | Trees: 60

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 360,000 → 390,000
✅ Completed | Trees: 65

Processing rows 390,000 → 420,000
✅ Completed | Trees: 70

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 420,000 → 450,000
✅ Completed | Trees: 75

Processing rows 450,000 → 480,000
✅ Completed | Trees: 80

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 480,000 → 510,000
✅ Completed | Trees: 85

Processing rows 510,000 → 540,000
✅ Completed | Trees: 90

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 540,000 → 570,000
✅ Completed | Trees: 95

Processing rows 570,000 → 600,000
✅ Completed | Trees: 100

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 600,000 → 630,000
✅ Completed | Trees: 105

Processing rows 630,000 → 660,000
✅ Completed | Trees: 110

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 660,000 → 690,000
✅ Completed | Trees: 115

Processing rows 690,000 → 720,000
✅ Completed | Trees: 120

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 720,000 → 750,000
✅ Completed | Trees: 125

Processing rows 750,000 → 780,000
✅ Completed | Trees: 130

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 780,000 → 810,000
✅ Completed | Trees: 135

Processing rows 810,000 → 840,000
✅ Completed | Trees: 140

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 840,000 → 870,000
✅ Completed | Trees: 145

Processing rows 870,000 → 900,000
✅ Completed | Trees: 150

Processing rows 900,000 → 930,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 155

Processing rows 930,000 → 960,000
✅ Completed | Trees: 160

Processing rows 960,000 → 990,000
✅ Completed | Trees: 165

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 990,000 → 1,020,000
✅ Completed | Trees: 170

Processing rows 1,020,000 → 1,050,000
✅ Completed | Trees: 175

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,050,000 → 1,080,000
✅ Completed | Trees: 180

Processing rows 1,080,000 → 1,110,000
✅ Completed | Trees: 185

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,110,000 → 1,140,000
✅ Completed | Trees: 190

Processing rows 1,140,000 → 1,170,000
✅ Completed | Trees: 195

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,170,000 → 1,200,000
✅ Completed | Trees: 200

Processing rows 1,200,000 → 1,230,000
✅ Completed | Trees: 205

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,230,000 → 1,260,000
✅ Completed | Trees: 210

Processing rows 1,260,000 → 1,290,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 215

Processing rows 1,290,000 → 1,320,000
✅ Completed | Trees: 220

Processing rows 1,320,000 → 1,350,000
✅ Completed | Trees: 225

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,350,000 → 1,380,000
✅ Completed | Trees: 230

Processing rows 1,380,000 → 1,410,000
✅ Completed | Trees: 235

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,410,000 → 1,440,000
✅ Completed | Trees: 240

Processing rows 1,440,000 → 1,470,000
✅ Completed | Trees: 245

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,470,000 → 1,500,000
✅ Completed | Trees: 250

Processing rows 1,500,000 → 1,530,000
✅ Completed | Trees: 255

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,530,000 → 1,560,000
✅ Completed | Trees: 260

Processing rows 1,560,000 → 1,590,000
✅ Completed | Trees: 265

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,590,000 → 1,620,000
✅ Completed | Trees: 270

Processing rows 1,620,000 → 1,650,000
✅ Completed | Trees: 275

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,650,000 → 1,680,000
✅ Completed | Trees: 280

Processing rows 1,680,000 → 1,710,000
✅ Completed | Trees: 285

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,710,000 → 1,740,000
✅ Completed | Trees: 290

Processing rows 1,740,000 → 1,770,000
✅ Completed | Trees: 295

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,770,000 → 1,778,193
✅ Completed | Trees: 300

In [54]:
X_test_transformed = tr1.transform(X_test)
y_pred = model.predict(X_test_transformed)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.8204877302614559
              precision    recall  f1-score   support

           0       1.00      0.82      0.90    443358
           1       0.01      0.90      0.03      1191

    accuracy                           0.82    444549
   macro avg       0.51      0.86      0.46    444549
weighted avg       1.00      0.82      0.90    444549

[[363677  79681]
 [   121   1070]]

In [56]:
from sklearn.linear_model import SGDClassifier

In [81]:
from sklearn.utils.class_weight import compute_class_weight
classes = np.unique(y_train)

# class_weights = {         This is the first hyperparameter where i get the best accuracy THIRD
#     0: 0.5,
#     1: 50
# }

# Now this is the best accuracy model  FIRST
class_weights = {         
    0: 1,
    1: 20
}

# class_weights = {         This is the second
#     0: 1,
#     1: 30
# }
# class_weights = {
#     0: 1,
#     1: 50
# }

model = SGDClassifier(
    loss='hinge',
    alpha=0.0001,
    max_iter=1000,
    tol=1e-3,
    random_state=42
)

batch_size = 30_000

for start in range(0, len(X_train), batch_size):

    end = min(start + batch_size, len(X_train))

    X_batch = X_train.iloc[start:end]
    y_batch = y_train.iloc[start:end]

    X_batch_transformed = tr1.transform(X_batch)

    sample_weights = np.array([
        class_weights[label]
        for label in y_batch
    ])

    model.partial_fit(
        X_batch_transformed,
        y_batch,
        classes=classes,
        sample_weight=sample_weights
    )

    print(f"✅ Completed: {start:,} → {end:,}")

    del X_batch
    del y_batch
    del X_batch_transformed
    del sample_weights

    gc.collect()

✅ Completed: 0 → 30,000
✅ Completed: 30,000 → 60,000
✅ Completed: 60,000 → 90,000
✅ Completed: 90,000 → 120,000
✅ Completed: 120,000 → 150,000
✅ Completed: 150,000 → 180,000
✅ Completed: 180,000 → 210,000
✅ Completed: 210,000 → 240,000
✅ Completed: 240,000 → 270,000
✅ Completed: 270,000 → 300,000
✅ Completed: 300,000 → 330,000
✅ Completed: 330,000 → 360,000
✅ Completed: 360,000 → 390,000
✅ Completed: 390,000 → 420,000
✅ Completed: 420,000 → 450,000
✅ Completed: 450,000 → 480,000
✅ Completed: 480,000 → 510,000
✅ Completed: 510,000 → 540,000
✅ Completed: 540,000 → 570,000
✅ Completed: 570,000 → 600,000
✅ Completed: 600,000 → 630,000
✅ Completed: 630,000 → 660,000
✅ Completed: 660,000 → 690,000
✅ Completed: 690,000 → 720,000
✅ Completed: 720,000 → 750,000
✅ Completed: 750,000 → 780,000
✅ Completed: 780,000 → 810,000
✅ Completed: 810,000 → 840,000
✅ Completed: 840,000 → 870,000
✅ Completed: 870,000 → 900,000
✅ Completed: 900,000 → 930,000
✅ Completed: 930,000 → 960,000
✅ Completed: 960,000 → 990,000
✅ Completed: 990,000 → 1,020,000
✅ Completed: 1,020,000 → 1,050,000
✅ Completed: 1,050,000 → 1,080,000
✅ Completed: 1,080,000 → 1,110,000
✅ Completed: 1,110,000 → 1,140,000
✅ Completed: 1,140,000 → 1,170,000
✅ Completed: 1,170,000 → 1,200,000
✅ Completed: 1,200,000 → 1,230,000
✅ Completed: 1,230,000 → 1,260,000
✅ Completed: 1,260,000 → 1,290,000
✅ Completed: 1,290,000 → 1,320,000
✅ Completed: 1,320,000 → 1,350,000
✅ Completed: 1,350,000 → 1,380,000
✅ Completed: 1,380,000 → 1,410,000
✅ Completed: 1,410,000 → 1,440,000
✅ Completed: 1,440,000 → 1,470,000
✅ Completed: 1,470,000 → 1,500,000
✅ Completed: 1,500,000 → 1,530,000
✅ Completed: 1,530,000 → 1,560,000
✅ Completed: 1,560,000 → 1,590,000
✅ Completed: 1,590,000 → 1,620,000
✅ Completed: 1,620,000 → 1,650,000
✅ Completed: 1,650,000 → 1,680,000
✅ Completed: 1,680,000 → 1,710,000
✅ Completed: 1,710,000 → 1,740,000
✅ Completed: 1,740,000 → 1,770,000
✅ Completed: 1,770,000 → 1,778,193

In [82]:
X_test_transformed = tr1.transform(X_test)
y_pred = model.predict(X_test_transformed)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.9897446625681309
              precision    recall  f1-score   support

           0       1.00      0.99      0.99    443358
           1       0.08      0.28      0.13      1191

    accuracy                           0.99    444549
   macro avg       0.54      0.64      0.56    444549
weighted avg       1.00      0.99      0.99    444549

[[439655   3703]
 [   856    335]]