In [7]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/asaniczka/amazon-uk-products-dataset-2023/amz_uk_processed_data.csv

In [8]:
df = pd.read_csv('/kaggle/input/datasets/asaniczka/amazon-uk-products-dataset-2023/amz_uk_processed_data.csv')

In [9]:
df.head()

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
0,B09B96TG33,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/71C3lbbeLs...,https://www.amazon.co.uk/dp/B09B96TG33,4.7,15308,21.99,False,0,Hi-Fi Speakers
1,B01HTH3C8S,"Anker Soundcore mini, Super-Portable Bluetooth...",https://m.media-amazon.com/images/I/61c5rSxwP0...,https://www.amazon.co.uk/dp/B01HTH3C8S,4.7,98099,23.99,True,0,Hi-Fi Speakers
2,B09B8YWXDF,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/61j3SEUjMJ...,https://www.amazon.co.uk/dp/B09B8YWXDF,4.7,15308,21.99,False,0,Hi-Fi Speakers
3,B09B8T5VGV,"Echo Dot with clock (5th generation, 2022 rele...",https://m.media-amazon.com/images/I/71yf6yTNWS...,https://www.amazon.co.uk/dp/B09B8T5VGV,4.7,7205,31.99,False,0,Hi-Fi Speakers
4,B09WX6QD65,Introducing Echo Pop | Full sound compact Wi-F...,https://m.media-amazon.com/images/I/613dEoF9-r...,https://www.amazon.co.uk/dp/B09WX6QD65,4.6,1881,17.99,False,0,Hi-Fi Speakers

In [10]:
df.shape

(2222742, 10)

In [11]:
df.tail()

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
2222737,B0CHSD7P2Q,"Motorbike Armour, Motorbike Clothing, Cycling ...",https://m.media-amazon.com/images/I/61ycPU7k4k...,https://www.amazon.co.uk/dp/B0CHSD7P2Q,0.0,0,22.34,False,0,Motorbike Clothing
2222738,B0B7B8FNBQ,PROFIRST Waterproof Motorcycle 2 Piece Ladies ...,https://m.media-amazon.com/images/I/51gkh0iYT5...,https://www.amazon.co.uk/dp/B0B7B8FNBQ,0.0,0,97.99,False,0,Motorbike Clothing
2222739,B0BD5FL5FB,Men’s Motorcycle Motorbike Biker Trousers Kevl...,https://m.media-amazon.com/images/I/81gJgaMHg4...,https://www.amazon.co.uk/dp/B0BD5FL5FB,0.0,0,52.99,False,0,Motorbike Clothing
2222740,B008OYLL4I,Texpeed Mens Motorcycle Motorbike Biker Trouse...,https://m.media-amazon.com/images/I/81KQ5askGG...,https://www.amazon.co.uk/dp/B008OYLL4I,4.3,404,79.99,False,0,Motorbike Clothing
2222741,B08P3W9B3T,RIDEX CJ223 Motorcycle Motorbike Jacket Armour...,https://m.media-amazon.com/images/I/61QaDygK8m...,https://www.amazon.co.uk/dp/B08P3W9B3T,4.5,34,53.99,False,0,Motorbike Clothing

In [12]:
df.sample(2)

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
193905,B00HGGN1KC,Eurotone 4er SET Tonerkartusche compatible wit...,https://m.media-amazon.com/images/I/71gI725xu7...,https://www.amazon.co.uk/dp/B00HGGN1KC,0.0,0,72.66,False,0,Computer Printers
1308243,B0BZ6LFNVL,topp 18536 Puzzle Advent Calendar,https://m.media-amazon.com/images/I/71mzGskdZN...,https://www.amazon.co.uk/dp/B0BZ6LFNVL,0.0,0,43.19,False,0,Toy Advent Calendars

In [13]:
df.isna().sum()

asin                 0
title                0
imgUrl               0
productURL           0
stars                0
reviews              0
price                0
isBestSeller         0
boughtInLastMonth    0
categoryName         0
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2222742 entries, 0 to 2222741
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   asin               object
 1   title              object
 2   imgUrl             object
 3   productURL         object
 4   stars              float64
 5   reviews            int64
 6   price              float64
 7   isBestSeller       bool
 8   boughtInLastMonth  int64
 9   categoryName       object
dtypes: bool(1), float64(2), int64(2), object(5)
memory usage: 154.7+ MB

In [15]:
df.describe()

              stars       reviews         price  boughtInLastMonth
count  2.222742e+06  2.222742e+06  2.222742e+06       2.222742e+06
mean   2.031870e+00  3.821617e+02  9.425737e+01       1.856902e+01
std    2.185497e+00  5.020752e+03  3.606225e+02       1.919030e+02
min    0.000000e+00  0.000000e+00  0.000000e+00       0.000000e+00
25%    0.000000e+00  0.000000e+00  1.000000e+01       0.000000e+00
50%    0.000000e+00  0.000000e+00  1.990000e+01       0.000000e+00
75%    4.400000e+00  4.400000e+01  4.771000e+01       0.000000e+00
max    5.000000e+00  1.356658e+06  1.000000e+05       5.000000e+04

In [16]:
df.corr(numeric_only = True)

,stars,reviews,price,isBestSeller,boughtInLastMonth
stars,1.000000,0.085124,-0.122505,0.056826,0.106259
reviews,0.085124,1.000000,-0.012482,0.061835,0.095229
price,-0.122505,-0.012482,1.000000,-0.010241,-0.021390
isBestSeller,0.056826,0.061835,-0.010241,1.000000,0.222299
boughtInLastMonth,0.106259,0.095229,-0.021390,0.222299,1.000000

In [17]:
df['isBestSeller']

0          False
1           True
2          False
3          False
4          False
           ...
2222737    False
2222738    False
2222739    False
2222740    False
2222741    False
Name: isBestSeller, Length: 2222742, dtype: bool

In [18]:
num_cols = df.select_dtypes(include='number')

In [19]:
cat_cols = df.select_dtypes(exclude = 'number')

In [20]:
num_cols

         stars  reviews  price  boughtInLastMonth
0          4.7    15308  21.99                  0
1          4.7    98099  23.99                  0
2          4.7    15308  21.99                  0
3          4.7     7205  31.99                  0
4          4.6     1881  17.99                  0
...        ...      ...    ...                ...
2222737    0.0        0  22.34                  0
2222738    0.0        0  97.99                  0
2222739    0.0        0  52.99                  0
2222740    4.3      404  79.99                  0
2222741    4.5       34  53.99                  0

[2222742 rows x 4 columns]

In [21]:
cat_cols

,asin,title,imgUrl,productURL,isBestSeller,categoryName
0,B09B96TG33,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/71C3lbbeLs...,https://www.amazon.co.uk/dp/B09B96TG33,False,Hi-Fi Speakers
1,B01HTH3C8S,"Anker Soundcore mini, Super-Portable Bluetooth...",https://m.media-amazon.com/images/I/61c5rSxwP0...,https://www.amazon.co.uk/dp/B01HTH3C8S,True,Hi-Fi Speakers
2,B09B8YWXDF,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/61j3SEUjMJ...,https://www.amazon.co.uk/dp/B09B8YWXDF,False,Hi-Fi Speakers
3,B09B8T5VGV,"Echo Dot with clock (5th generation, 2022 rele...",https://m.media-amazon.com/images/I/71yf6yTNWS...,https://www.amazon.co.uk/dp/B09B8T5VGV,False,Hi-Fi Speakers
4,B09WX6QD65,Introducing Echo Pop | Full sound compact Wi-F...,https://m.media-amazon.com/images/I/613dEoF9-r...,https://www.amazon.co.uk/dp/B09WX6QD65,False,Hi-Fi Speakers
...,...,...,...,...,...,...
2222737,B0CHSD7P2Q,"Motorbike Armour, Motorbike Clothing, Cycling ...",https://m.media-amazon.com/images/I/61ycPU7k4k...,https://www.amazon.co.uk/dp/B0CHSD7P2Q,False,Motorbike Clothing
2222738,B0B7B8FNBQ,PROFIRST Waterproof Motorcycle 2 Piece Ladies ...,https://m.media-amazon.com/images/I/51gkh0iYT5...,https://www.amazon.co.uk/dp/B0B7B8FNBQ,False,Motorbike Clothing
2222739,B0BD5FL5FB,Men’s Motorcycle Motorbike Biker Trousers Kevl...,https://m.media-amazon.com/images/I/81gJgaMHg4...,https://www.amazon.co.uk/dp/B0BD5FL5FB,False,Motorbike Clothing
2222740,B008OYLL4I,Texpeed Mens Motorcycle Motorbike Biker Trouse...,https://m.media-amazon.com/images/I/81KQ5askGG...,https://www.amazon.co.uk/dp/B008OYLL4I,False,Motorbike Clothing
2222741,B08P3W9B3T,RIDEX CJ223 Motorcycle Motorbike Jacket Armour...,https://m.media-amazon.com/images/I/61QaDygK8m...,https://www.amazon.co.uk/dp/B08P3W9B3T,False,Motorbike Clothing

In [22]:
df['imgUrl']

0          https://m.media-amazon.com/images/I/71C3lbbeLs...
1          https://m.media-amazon.com/images/I/61c5rSxwP0...
2          https://m.media-amazon.com/images/I/61j3SEUjMJ...
3          https://m.media-amazon.com/images/I/71yf6yTNWS...
4          https://m.media-amazon.com/images/I/613dEoF9-r...
                                 ...
2222737    https://m.media-amazon.com/images/I/61ycPU7k4k...
2222738    https://m.media-amazon.com/images/I/51gkh0iYT5...
2222739    https://m.media-amazon.com/images/I/81gJgaMHg4...
2222740    https://m.media-amazon.com/images/I/81KQ5askGG...
2222741    https://m.media-amazon.com/images/I/61QaDygK8m...
Name: imgUrl, Length: 2222742, dtype: object

In [23]:
df.shape

(2222742, 10)

In [24]:
df.columns

Index(['asin', 'title', 'imgUrl', 'productURL', 'stars', 'reviews', 'price',
       'isBestSeller', 'boughtInLastMonth', 'categoryName'],
      dtype='object')

In [25]:
num_cols.columns

Index(['stars', 'reviews', 'price', 'boughtInLastMonth'], dtype='object')

In [26]:
cat_cols.columns

Index(['asin', 'title', 'imgUrl', 'productURL', 'isBestSeller',
       'categoryName'],
      dtype='object')

In [27]:
num_cols['price']

0          21.99
1          23.99
2          21.99
3          31.99
4          17.99
           ...
2222737    22.34
2222738    97.99
2222739    52.99
2222740    79.99
2222741    53.99
Name: price, Length: 2222742, dtype: float64

In [28]:
#Converting Pounds Into Rupees
df['price'] = df['price'] * 127.43

In [29]:
df['price']

0           2802.1857
1           3057.0457
2           2802.1857
3           4076.4857
4           2292.4657
              ...
2222737     2846.7862
2222738    12486.8657
2222739     6752.5157
2222740    10193.1257
2222741     6879.9457
Name: price, Length: 2222742, dtype: float64

In [30]:
df['price'] = df['price'].apply(
    lambda x: np.ceil(x) if x % 1 >= 0.5 else np.floor(x)
)

In [31]:
df['price']

0           2802.0
1           3057.0
2           2802.0
3           4076.0
4           2292.0
            ...
2222737     2847.0
2222738    12487.0
2222739     6753.0
2222740    10193.0
2222741     6880.0
Name: price, Length: 2222742, dtype: float64

In [32]:
df['productURL']

0          https://www.amazon.co.uk/dp/B09B96TG33
1          https://www.amazon.co.uk/dp/B01HTH3C8S
2          https://www.amazon.co.uk/dp/B09B8YWXDF
3          https://www.amazon.co.uk/dp/B09B8T5VGV
4          https://www.amazon.co.uk/dp/B09WX6QD65
                            ...
2222737    https://www.amazon.co.uk/dp/B0CHSD7P2Q
2222738    https://www.amazon.co.uk/dp/B0B7B8FNBQ
2222739    https://www.amazon.co.uk/dp/B0BD5FL5FB
2222740    https://www.amazon.co.uk/dp/B008OYLL4I
2222741    https://www.amazon.co.uk/dp/B08P3W9B3T
Name: productURL, Length: 2222742, dtype: object

In [33]:
df.sample(2)

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
1515425,B0BKQVRH58,Christmas Stocking Kilim Design Fabric Double ...,https://m.media-amazon.com/images/I/91DTIx1xHi...,https://www.amazon.co.uk/dp/B0BKQVRH58,0.0,0,3173.0,False,0,Handmade Home Décor
1860538,B08YZ2C9RF,GB BELTING LIMITED Horizon Fitness 4.1T TM136 ...,https://m.media-amazon.com/images/I/81bR4m5f+6...,https://www.amazon.co.uk/dp/B08YZ2C9RF,0.0,0,14182.0,False,0,Sports & Outdoors

In [34]:
df['categoryName'].value_counts()

categoryName
Sports & Outdoors                 826076
Skin Care                          18755
Fragrances                         18563
Make-up                            18453
Manicure & Pedicure Products       17212
                                   ...
Torches                               64
Smart Home Security & Lighting        57
Lighting                              50
Smart Speakers                        25
Cameras                               12
Name: count, Length: 296, dtype: int64

In [35]:
df.drop(columns = ['imgUrl','productURL','title'],axis = 1,inplace = True)

In [36]:
df.sample(5)

,asin,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
821374,B09RJKS6T2,4.0,2,1655.0,False,0,Sports Toys & Outdoor
1091470,B09STCVT7L,4.4,99,432.0,False,0,Safety & Security
1894675,B0CJPVLZT7,0.0,0,4358.0,False,0,Sports & Outdoors
1081350,B015GW1A9G,3.9,130,590.0,False,0,"Painting Supplies, Tools & Wall Treatments"
774684,B0B4YLD561,3.8,4,22988.0,False,0,Ski Clothing

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,LabelEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [38]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,roc_curve,roc_auc_score

In [39]:
df.drop(columns = ['asin'],axis = 1,inplace = True)

In [40]:
X = df.drop(columns = ['isBestSeller'],axis = 1)

In [41]:
df['isBestSeller'] = df['isBestSeller'].apply(lambda x: 1 if x else 0)

In [42]:
y = df['isBestSeller']

In [43]:
df['isBestSeller'].value_counts()

isBestSeller
0    2216724
1       6018
Name: count, dtype: int64

In [44]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [45]:
X_train.shape

(1778193, 5)

In [46]:
X_test.shape

(444549, 5)

In [47]:
y_train.shape

(1778193,)

In [48]:
y_test.shape

(444549,)

In [49]:
X_train

,stars,reviews,price,boughtInLastMonth,categoryName
757021,4.6,126,28140.0,0,Sports & Outdoors
1953809,0.0,0,751.0,0,Sports & Outdoors
1305660,0.0,0,2086.0,0,Toy Advent Calendars
1440599,0.0,0,1451.0,0,Sports & Outdoors
1809750,5.0,1,858.0,0,Remote & App-Controlled Devices
...,...,...,...,...,...
1570006,4.7,308,12103.0,0,Camera & Photo Accessories
732180,0.0,0,48296.0,0,Sports & Outdoors
110268,5.0,4,1911.0,0,Handmade Gifts
1692743,0.0,0,28083.0,0,Sports & Outdoors
2219110,0.0,0,2306.0,0,Table Tennis

In [50]:
tr1 = ColumnTransformer(transformers=[
    (
        'OneHotEncoding',
        OneHotEncoder(
            sparse_output=True,
            handle_unknown='ignore'
        ),
        ['categoryName']
    ),
    (
        'StandardScaling',
        StandardScaler(),
        ['stars', 'reviews', 'price', 'boughtInLastMonth']
    )
])

In [51]:
tr1

ColumnTransformer(transformers=[('OneHotEncoding',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['categoryName']),
                                ('StandardScaling', StandardScaler(),
                                 ['stars', 'reviews', 'price',
                                  'boughtInLastMonth'])])

In [52]:
pipe1 = Pipeline(steps=[
    ('preprocessing', tr1),
    ('model', RandomForestClassifier(
        n_estimators=100,
        max_depth=15,
        min_samples_split=10,
        min_samples_leaf=4,
        max_features='sqrt',
        max_leaf_nodes=100,
        min_impurity_decrease=0.01,
        bootstrap=True,
        max_samples=0.8,
        class_weight='balanced',
        random_state=42,
        n_jobs=-1,
        warm_start=True
    ))
])

In [53]:
# # 30K
# X_batch = X_train.iloc[:30_000]
# y_batch = y_train.iloc[:30_000]

# pipe1.fit(X_batch, y_batch)

In [54]:
X_fit = X_train.iloc[:30_000]

tr1.fit(X_fit)

print("✅ Preprocessor fitted successfully")

del X_fit

import gc
gc.collect()

✅ Preprocessor fitted successfully

23

In [55]:
X_test_batch = X_train.iloc[:100]

X_test_transformed = tr1.transform(X_test_batch)

print("✅ Transform successful")
print("Shape:", X_test_transformed.shape)

del X_test_batch, X_test_transformed
gc.collect()

✅ Transform successful
Shape: (100, 294)

23

In [56]:
model = RandomForestClassifier(
    n_estimators=10,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=4,
    max_features='sqrt',
    max_leaf_nodes=100,
    min_impurity_decrease=0.01,
    bootstrap=True,
    max_samples=0.8,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    warm_start=True
)

batch_size = 30_000
trees_per_batch = 5

for start in range(0, len(X_train), batch_size):

    end = min(start + batch_size, len(X_train))

    print(f"\nProcessing rows {start:,} → {end:,}")

    X_batch = X_train.iloc[start:end]
    y_batch = y_train.iloc[start:end]

    X_batch_transformed = tr1.transform(X_batch)

    model.n_estimators += trees_per_batch

    model.fit(X_batch_transformed, y_batch)

    print(f"✅ Completed | Trees: {model.n_estimators}")

    del X_batch
    del y_batch
    del X_batch_transformed

    gc.collect()

Processing rows 0 → 30,000
✅ Completed | Trees: 15

Processing rows 30,000 → 60,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 20

Processing rows 60,000 → 90,000
✅ Completed | Trees: 25

Processing rows 90,000 → 120,000
✅ Completed | Trees: 30

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 120,000 → 150,000
✅ Completed | Trees: 35

Processing rows 150,000 → 180,000
✅ Completed | Trees: 40

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 180,000 → 210,000
✅ Completed | Trees: 45

Processing rows 210,000 → 240,000
✅ Completed | Trees: 50

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 240,000 → 270,000
✅ Completed | Trees: 55

Processing rows 270,000 → 300,000
✅ Completed | Trees: 60

Processing rows 300,000 → 330,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 65

Processing rows 330,000 → 360,000
✅ Completed | Trees: 70

Processing rows 360,000 → 390,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 75

Processing rows 390,000 → 420,000
✅ Completed | Trees: 80

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 420,000 → 450,000
✅ Completed | Trees: 85

Processing rows 450,000 → 480,000
✅ Completed | Trees: 90

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 480,000 → 510,000
✅ Completed | Trees: 95

Processing rows 510,000 → 540,000
✅ Completed | Trees: 100

Processing rows 540,000 → 570,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 105

Processing rows 570,000 → 600,000
✅ Completed | Trees: 110

Processing rows 600,000 → 630,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 115

Processing rows 630,000 → 660,000
✅ Completed | Trees: 120

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 660,000 → 690,000
✅ Completed | Trees: 125

Processing rows 690,000 → 720,000
✅ Completed | Trees: 130

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 720,000 → 750,000
✅ Completed | Trees: 135

Processing rows 750,000 → 780,000
✅ Completed | Trees: 140

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 780,000 → 810,000
✅ Completed | Trees: 145

Processing rows 810,000 → 840,000
✅ Completed | Trees: 150

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 840,000 → 870,000
✅ Completed | Trees: 155

Processing rows 870,000 → 900,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 160

Processing rows 900,000 → 930,000
✅ Completed | Trees: 165

Processing rows 930,000 → 960,000
✅ Completed | Trees: 170

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 960,000 → 990,000
✅ Completed | Trees: 175

Processing rows 990,000 → 1,020,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 180

Processing rows 1,020,000 → 1,050,000
✅ Completed | Trees: 185

Processing rows 1,050,000 → 1,080,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 190

Processing rows 1,080,000 → 1,110,000
✅ Completed | Trees: 195

Processing rows 1,110,000 → 1,140,000
✅ Completed | Trees: 200

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,140,000 → 1,170,000
✅ Completed | Trees: 205

Processing rows 1,170,000 → 1,200,000
✅ Completed | Trees: 210

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,200,000 → 1,230,000
✅ Completed | Trees: 215

Processing rows 1,230,000 → 1,260,000
✅ Completed | Trees: 220

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,260,000 → 1,290,000
✅ Completed | Trees: 225

Processing rows 1,290,000 → 1,320,000
✅ Completed | Trees: 230

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,320,000 → 1,350,000
✅ Completed | Trees: 235

Processing rows 1,350,000 → 1,380,000
✅ Completed | Trees: 240

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,380,000 → 1,410,000
✅ Completed | Trees: 245

Processing rows 1,410,000 → 1,440,000
✅ Completed | Trees: 250

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,440,000 → 1,470,000
✅ Completed | Trees: 255

Processing rows 1,470,000 → 1,500,000
✅ Completed | Trees: 260

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,500,000 → 1,530,000
✅ Completed | Trees: 265

Processing rows 1,530,000 → 1,560,000
✅ Completed | Trees: 270

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,560,000 → 1,590,000
✅ Completed | Trees: 275

Processing rows 1,590,000 → 1,620,000
✅ Completed | Trees: 280

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,620,000 → 1,650,000
✅ Completed | Trees: 285

Processing rows 1,650,000 → 1,680,000
✅ Completed | Trees: 290

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,680,000 → 1,710,000
✅ Completed | Trees: 295

Processing rows 1,710,000 → 1,740,000
✅ Completed | Trees: 300

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,740,000 → 1,770,000
✅ Completed | Trees: 305

Processing rows 1,770,000 → 1,778,193
✅ Completed | Trees: 310

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

In [57]:
X_test_transformed = tr1.transform(X_test)
y_pred = model.predict(X_test_transformed)

In [58]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8311277272021756
              precision    recall  f1-score   support

           0       1.00      0.83      0.91    443358
           1       0.01      0.90      0.03      1191

    accuracy                           0.83    444549
   macro avg       0.51      0.86      0.47    444549
weighted avg       1.00      0.83      0.91    444549

In [59]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[368409  74949]
 [   123   1068]]

In [60]:
model = RandomForestClassifier(
    n_estimators=5,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=4,
    max_features='sqrt',
    max_leaf_nodes=100,
    min_impurity_decrease=0.01,
    bootstrap=True,
    max_samples=0.8,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    warm_start=True
)

batch_size = 30_000
trees_per_batch = 5

for start in range(0, len(X_train), batch_size):

    end = min(start + batch_size, len(X_train))

    print(f"\nProcessing rows {start:,} → {end:,}")

    # Get batch
    X_batch = X_train.iloc[start:end]
    y_batch = y_train.iloc[start:end]

    # Transform batch
    X_batch_transformed = tr1.transform(X_batch)

    # Add new trees
    if start != 0:
        model.n_estimators += trees_per_batch

    # Train
    model.fit(
        X_batch_transformed,
        y_batch
    )

    print(f"✅ Completed | Trees: {model.n_estimators}")

    # Free memory
    del X_batch
    del y_batch
    del X_batch_transformed

    gc.collect()

Processing rows 0 → 30,000
✅ Completed | Trees: 5

Processing rows 30,000 → 60,000
✅ Completed | Trees: 10

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 60,000 → 90,000
✅ Completed | Trees: 15

Processing rows 90,000 → 120,000
✅ Completed | Trees: 20

Processing rows 120,000 → 150,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 25

Processing rows 150,000 → 180,000
✅ Completed | Trees: 30

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 180,000 → 210,000
✅ Completed | Trees: 35

Processing rows 210,000 → 240,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 40

Processing rows 240,000 → 270,000
✅ Completed | Trees: 45

Processing rows 270,000 → 300,000
✅ Completed | Trees: 50

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 300,000 → 330,000
✅ Completed | Trees: 55

Processing rows 330,000 → 360,000
✅ Completed | Trees: 60

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 360,000 → 390,000
✅ Completed | Trees: 65

Processing rows 390,000 → 420,000
✅ Completed | Trees: 70

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 420,000 → 450,000
✅ Completed | Trees: 75

Processing rows 450,000 → 480,000
✅ Completed | Trees: 80

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 480,000 → 510,000
✅ Completed | Trees: 85

Processing rows 510,000 → 540,000
✅ Completed | Trees: 90

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 540,000 → 570,000
✅ Completed | Trees: 95

Processing rows 570,000 → 600,000

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

✅ Completed | Trees: 100

Processing rows 600,000 → 630,000
✅ Completed | Trees: 105

Processing rows 630,000 → 660,000
✅ Completed | Trees: 110

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 660,000 → 690,000
✅ Completed | Trees: 115

Processing rows 690,000 → 720,000
✅ Completed | Trees: 120

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 720,000 → 750,000
✅ Completed | Trees: 125

Processing rows 750,000 → 780,000
✅ Completed | Trees: 130

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 780,000 → 810,000
✅ Completed | Trees: 135

Processing rows 810,000 → 840,000
✅ Completed | Trees: 140

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 840,000 → 870,000
✅ Completed | Trees: 145

Processing rows 870,000 → 900,000
✅ Completed | Trees: 150

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 900,000 → 930,000
✅ Completed | Trees: 155

Processing rows 930,000 → 960,000
✅ Completed | Trees: 160

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 960,000 → 990,000
✅ Completed | Trees: 165

Processing rows 990,000 → 1,020,000
✅ Completed | Trees: 170

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,020,000 → 1,050,000
✅ Completed | Trees: 175

Processing rows 1,050,000 → 1,080,000
✅ Completed | Trees: 180

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,080,000 → 1,110,000
✅ Completed | Trees: 185

Processing rows 1,110,000 → 1,140,000
✅ Completed | Trees: 190

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,140,000 → 1,170,000
✅ Completed | Trees: 195

Processing rows 1,170,000 → 1,200,000
✅ Completed | Trees: 200

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,200,000 → 1,230,000
✅ Completed | Trees: 205

Processing rows 1,230,000 → 1,260,000
✅ Completed | Trees: 210

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,260,000 → 1,290,000
✅ Completed | Trees: 215

Processing rows 1,290,000 → 1,320,000
✅ Completed | Trees: 220

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,320,000 → 1,350,000
✅ Completed | Trees: 225

Processing rows 1,350,000 → 1,380,000
✅ Completed | Trees: 230

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,380,000 → 1,410,000
✅ Completed | Trees: 235

Processing rows 1,410,000 → 1,440,000
✅ Completed | Trees: 240

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,440,000 → 1,470,000
✅ Completed | Trees: 245

Processing rows 1,470,000 → 1,500,000
✅ Completed | Trees: 250

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,500,000 → 1,530,000
✅ Completed | Trees: 255

Processing rows 1,530,000 → 1,560,000
✅ Completed | Trees: 260

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,560,000 → 1,590,000
✅ Completed | Trees: 265

Processing rows 1,590,000 → 1,620,000
✅ Completed | Trees: 270

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,620,000 → 1,650,000
✅ Completed | Trees: 275

Processing rows 1,650,000 → 1,680,000
✅ Completed | Trees: 280

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,680,000 → 1,710,000
✅ Completed | Trees: 285

Processing rows 1,710,000 → 1,740,000
✅ Completed | Trees: 290

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Processing rows 1,740,000 → 1,770,000
✅ Completed | Trees: 295

Processing rows 1,770,000 → 1,778,193
✅ Completed | Trees: 300

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

In [61]:
X_test_transformed = tr1.transform(X_test)
y_pred = model.predict(X_test_transformed)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.8204877302614559
              precision    recall  f1-score   support

           0       1.00      0.82      0.90    443358
           1       0.01      0.90      0.03      1191

    accuracy                           0.82    444549
   macro avg       0.51      0.86      0.46    444549
weighted avg       1.00      0.82      0.90    444549

[[363677  79681]
 [   121   1070]]

In [62]:
from sklearn.linear_model import SGDClassifier

In [63]:
from sklearn.utils.class_weight import compute_class_weight
classes = np.unique(y_train)

# class_weights = {         This is the first hyperparameter where i get the best accuracy THIRD
#     0: 0.5,
#     1: 50
# }

# Now this is the best accuracy model  FIRST
class_weights = {         
    0: 1,
    1: 20
}

# class_weights = {         This is the second
#     0: 1,
#     1: 30
# }
# class_weights = {
#     0: 1,
#     1: 50
# }

model = SGDClassifier(
    loss='hinge',
    alpha=0.0001,
    max_iter=1000,
    tol=1e-3,
    random_state=42
)

batch_size = 30_000

for start in range(0, len(X_train), batch_size):

    end = min(start + batch_size, len(X_train))

    X_batch = X_train.iloc[start:end]
    y_batch = y_train.iloc[start:end]

    X_batch_transformed = tr1.transform(X_batch)

    sample_weights = np.array([
        class_weights[label]
        for label in y_batch
    ])

    model.partial_fit(
        X_batch_transformed,
        y_batch,
        classes=classes,
        sample_weight=sample_weights
    )

    print(f"✅ Completed: {start:,} → {end:,}")

    del X_batch
    del y_batch
    del X_batch_transformed
    del sample_weights

    gc.collect()

✅ Completed: 0 → 30,000
✅ Completed: 30,000 → 60,000
✅ Completed: 60,000 → 90,000
✅ Completed: 90,000 → 120,000
✅ Completed: 120,000 → 150,000
✅ Completed: 150,000 → 180,000
✅ Completed: 180,000 → 210,000
✅ Completed: 210,000 → 240,000
✅ Completed: 240,000 → 270,000
✅ Completed: 270,000 → 300,000
✅ Completed: 300,000 → 330,000
✅ Completed: 330,000 → 360,000
✅ Completed: 360,000 → 390,000
✅ Completed: 390,000 → 420,000
✅ Completed: 420,000 → 450,000
✅ Completed: 450,000 → 480,000
✅ Completed: 480,000 → 510,000
✅ Completed: 510,000 → 540,000
✅ Completed: 540,000 → 570,000
✅ Completed: 570,000 → 600,000
✅ Completed: 600,000 → 630,000
✅ Completed: 630,000 → 660,000
✅ Completed: 660,000 → 690,000
✅ Completed: 690,000 → 720,000
✅ Completed: 720,000 → 750,000
✅ Completed: 750,000 → 780,000
✅ Completed: 780,000 → 810,000
✅ Completed: 810,000 → 840,000
✅ Completed: 840,000 → 870,000
✅ Completed: 870,000 → 900,000
✅ Completed: 900,000 → 930,000
✅ Completed: 930,000 → 960,000
✅ Completed: 960,000 → 990,000
✅ Completed: 990,000 → 1,020,000
✅ Completed: 1,020,000 → 1,050,000
✅ Completed: 1,050,000 → 1,080,000
✅ Completed: 1,080,000 → 1,110,000
✅ Completed: 1,110,000 → 1,140,000
✅ Completed: 1,140,000 → 1,170,000
✅ Completed: 1,170,000 → 1,200,000
✅ Completed: 1,200,000 → 1,230,000
✅ Completed: 1,230,000 → 1,260,000
✅ Completed: 1,260,000 → 1,290,000
✅ Completed: 1,290,000 → 1,320,000
✅ Completed: 1,320,000 → 1,350,000
✅ Completed: 1,350,000 → 1,380,000
✅ Completed: 1,380,000 → 1,410,000
✅ Completed: 1,410,000 → 1,440,000
✅ Completed: 1,440,000 → 1,470,000
✅ Completed: 1,470,000 → 1,500,000
✅ Completed: 1,500,000 → 1,530,000
✅ Completed: 1,530,000 → 1,560,000
✅ Completed: 1,560,000 → 1,590,000
✅ Completed: 1,590,000 → 1,620,000
✅ Completed: 1,620,000 → 1,650,000
✅ Completed: 1,650,000 → 1,680,000
✅ Completed: 1,680,000 → 1,710,000
✅ Completed: 1,710,000 → 1,740,000
✅ Completed: 1,740,000 → 1,770,000
✅ Completed: 1,770,000 → 1,778,193

In [64]:

classes = np.unique(y_train)

# Class weights for handling class imbalance
class_weights = {
    0: 1,
    1: 20
}

model = SGDClassifier(
    loss='log_loss',
    alpha=0.0001,
    max_iter=1000,
    tol=1e-3,
    random_state=42
)

# Feature weights
feature_weights = {
    'stars': 2.0,
    'reviews': 2.0,
    'price': 2.0,
    'boughtInLastMonth': 3.0,
    'categoryName': 1.0
}

# Get transformed feature names
feature_names = tr1.get_feature_names_out()

# Initialize weights for transformed features
weights = np.ones(len(feature_names))

for i, name in enumerate(feature_names):
    for feature, weight in feature_weights.items():
        if feature in name:
            weights[i] = weight

batch_size = 30_000

for start in range(0, len(X_train), batch_size):
    end = min(start + batch_size, len(X_train))

    X_batch = X_train.iloc[start:end]
    y_batch = y_train.iloc[start:end]

    X_batch_transformed = tr1.transform(X_batch)

    # Increase importance of selected features
    X_batch_transformed = X_batch_transformed.multiply(weights)

    # Apply class weights
    sample_weights = np.array([
        class_weights[label]
        for label in y_batch
    ])

    model.partial_fit(
        X_batch_transformed,
        y_batch,
        classes=classes,
        sample_weight=sample_weights
    )

    print(f"Completed: {start:,} → {end:,}")

    del X_batch, y_batch, X_batch_transformed, sample_weights
    gc.collect()

Completed: 0 → 30,000
Completed: 30,000 → 60,000
Completed: 60,000 → 90,000
Completed: 90,000 → 120,000
Completed: 120,000 → 150,000
Completed: 150,000 → 180,000
Completed: 180,000 → 210,000
Completed: 210,000 → 240,000
Completed: 240,000 → 270,000
Completed: 270,000 → 300,000
Completed: 300,000 → 330,000
Completed: 330,000 → 360,000
Completed: 360,000 → 390,000
Completed: 390,000 → 420,000
Completed: 420,000 → 450,000
Completed: 450,000 → 480,000
Completed: 480,000 → 510,000
Completed: 510,000 → 540,000
Completed: 540,000 → 570,000
Completed: 570,000 → 600,000
Completed: 600,000 → 630,000
Completed: 630,000 → 660,000
Completed: 660,000 → 690,000
Completed: 690,000 → 720,000
Completed: 720,000 → 750,000
Completed: 750,000 → 780,000
Completed: 780,000 → 810,000
Completed: 810,000 → 840,000
Completed: 840,000 → 870,000
Completed: 870,000 → 900,000
Completed: 900,000 → 930,000
Completed: 930,000 → 960,000
Completed: 960,000 → 990,000
Completed: 990,000 → 1,020,000
Completed: 1,020,000 → 1,050,000
Completed: 1,050,000 → 1,080,000
Completed: 1,080,000 → 1,110,000
Completed: 1,110,000 → 1,140,000
Completed: 1,140,000 → 1,170,000
Completed: 1,170,000 → 1,200,000
Completed: 1,200,000 → 1,230,000
Completed: 1,230,000 → 1,260,000
Completed: 1,260,000 → 1,290,000
Completed: 1,290,000 → 1,320,000
Completed: 1,320,000 → 1,350,000
Completed: 1,350,000 → 1,380,000
Completed: 1,380,000 → 1,410,000
Completed: 1,410,000 → 1,440,000
Completed: 1,440,000 → 1,470,000
Completed: 1,470,000 → 1,500,000
Completed: 1,500,000 → 1,530,000
Completed: 1,530,000 → 1,560,000
Completed: 1,560,000 → 1,590,000
Completed: 1,590,000 → 1,620,000
Completed: 1,620,000 → 1,650,000
Completed: 1,650,000 → 1,680,000
Completed: 1,680,000 → 1,710,000
Completed: 1,710,000 → 1,740,000
Completed: 1,740,000 → 1,770,000
Completed: 1,770,000 → 1,778,193

In [65]:
import numpy as np
import gc

from sklearn.linear_model import SGDClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

classes = np.unique(y_train)

class_weights = {
    0: 1,
    1: 20
}

model = SGDClassifier(
    loss='log_loss',       # Changed from hinge
    alpha=0.0001,
    max_iter=1000,
    tol=1e-3,
    random_state=42
)

batch_size = 30_000

for start in range(0, len(X_train), batch_size):

    end = min(start + batch_size, len(X_train))

    X_batch = X_train.iloc[start:end]
    y_batch = y_train.iloc[start:end]

    X_batch_transformed = tr1.transform(X_batch)

    sample_weights = np.array([
        class_weights[label]
        for label in y_batch
    ])

    model.partial_fit(
        X_batch_transformed,
        y_batch,
        classes=classes,
        sample_weight=sample_weights
    )

    print(f"Completed: {start:,} → {end:,}")

    del X_batch, y_batch, X_batch_transformed, sample_weights
    gc.collect()

Completed: 0 → 30,000
Completed: 30,000 → 60,000
Completed: 60,000 → 90,000
Completed: 90,000 → 120,000
Completed: 120,000 → 150,000
Completed: 150,000 → 180,000
Completed: 180,000 → 210,000
Completed: 210,000 → 240,000
Completed: 240,000 → 270,000
Completed: 270,000 → 300,000
Completed: 300,000 → 330,000
Completed: 330,000 → 360,000
Completed: 360,000 → 390,000
Completed: 390,000 → 420,000
Completed: 420,000 → 450,000
Completed: 450,000 → 480,000
Completed: 480,000 → 510,000
Completed: 510,000 → 540,000
Completed: 540,000 → 570,000
Completed: 570,000 → 600,000
Completed: 600,000 → 630,000
Completed: 630,000 → 660,000
Completed: 660,000 → 690,000
Completed: 690,000 → 720,000
Completed: 720,000 → 750,000
Completed: 750,000 → 780,000
Completed: 780,000 → 810,000
Completed: 810,000 → 840,000
Completed: 840,000 → 870,000
Completed: 870,000 → 900,000
Completed: 900,000 → 930,000
Completed: 930,000 → 960,000
Completed: 960,000 → 990,000
Completed: 990,000 → 1,020,000
Completed: 1,020,000 → 1,050,000
Completed: 1,050,000 → 1,080,000
Completed: 1,080,000 → 1,110,000
Completed: 1,110,000 → 1,140,000
Completed: 1,140,000 → 1,170,000
Completed: 1,170,000 → 1,200,000
Completed: 1,200,000 → 1,230,000
Completed: 1,230,000 → 1,260,000
Completed: 1,260,000 → 1,290,000
Completed: 1,290,000 → 1,320,000
Completed: 1,320,000 → 1,350,000
Completed: 1,350,000 → 1,380,000
Completed: 1,380,000 → 1,410,000
Completed: 1,410,000 → 1,440,000
Completed: 1,440,000 → 1,470,000
Completed: 1,470,000 → 1,500,000
Completed: 1,500,000 → 1,530,000
Completed: 1,530,000 → 1,560,000
Completed: 1,560,000 → 1,590,000
Completed: 1,590,000 → 1,620,000
Completed: 1,620,000 → 1,650,000
Completed: 1,650,000 → 1,680,000
Completed: 1,680,000 → 1,710,000
Completed: 1,710,000 → 1,740,000
Completed: 1,740,000 → 1,770,000
Completed: 1,770,000 → 1,778,193

In [66]:
X_test_transformed = tr1.transform(X_test)
y_pred = model.predict(X_test_transformed)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.9858575770050095
              precision    recall  f1-score   support

           0       1.00      0.99      0.99    443358
           1       0.07      0.38      0.12      1191

    accuracy                           0.99    444549
   macro avg       0.54      0.68      0.56    444549
weighted avg       1.00      0.99      0.99    444549

[[437813   5545]
 [   742    449]]

In [67]:
X_test_transformed = tr1.transform(X_test)

# Probability of positive class (class 1)
y_prob = model.predict_proba(X_test_transformed)[:, 1]

print("First 10 predicted probabilities:")
print(y_prob[:10])

# Convert probabilities into binary predictions
y_pred = (y_prob >= 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

First 10 predicted probabilities:
[9.27190136e-01 8.60624061e-12 7.48284302e-12 1.05970567e-11
 6.52559046e-12 2.67170782e-01 3.24465604e-01 2.94606975e-02
 9.93825515e-02 3.77608595e-02]
Accuracy: 0.9858575770050095
              precision    recall  f1-score   support

           0       1.00      0.99      0.99    443358
           1       0.07      0.38      0.12      1191

    accuracy                           0.99    444549
   macro avg       0.54      0.68      0.56    444549
weighted avg       1.00      0.99      0.99    444549

Confusion Matrix:
[[437813   5545]
 [   742    449]]
ROC-AUC: 0.9106809672440755

In [68]:
# import pickle

# with open('model.pkl', 'wb') as file:
#     pickle.dump(model, file)

In [71]:

import numpy as np
import gc

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin
from scipy import sparse


# 1. Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            'OneHotEncoding',
            OneHotEncoder(
                sparse_output=True,
                handle_unknown='ignore'
            ),
            ['categoryName']
        ),
        (
            'StandardScaling',
            StandardScaler(),
            ['stars', 'reviews', 'price', 'boughtInLastMonth']
        )
    ]
)


# 2. Fit the preprocessor
# Keep your existing approach of fitting on 30,000 rows
X_fit = X_train.iloc[:30_000]

preprocessor.fit(X_fit)

del X_fit
gc.collect()


# 3. Define feature weights
feature_weights = {
    'stars': 2.0,
    'reviews': 2.0,
    'price': 2.0,
    'boughtInLastMonth': 3.0,
    'categoryName': 1.0
}

feature_names = preprocessor.get_feature_names_out()

weights = np.ones(len(feature_names))

for i, name in enumerate(feature_names):
    for feature, weight in feature_weights.items():
        if feature in name:
            weights[i] = weight


# 4. Custom transformer for feature weighting
class FeatureWeighter(BaseEstimator, TransformerMixin):

    def __init__(self, weights):
        self.weights = weights

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        if sparse.issparse(X):
            return X.multiply(self.weights).tocsr()

        return X * self.weights


feature_weighter = FeatureWeighter(weights)


# 5. Classifier
class_weights = {
    0: 1,
    1: 20
}

classifier = SGDClassifier(
    loss='log_loss',
    alpha=0.0001,
    max_iter=1000,
    tol=1e-3,
    random_state=42
)


# 6. Create one complete pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('feature_weighter', feature_weighter),
    ('classifier', classifier)
])


# 7. Incremental batch training
classes = np.unique(y_train)
batch_size = 30_000

for start in range(0, len(X_train), batch_size):

    end = min(start + batch_size, len(X_train))

    X_batch = X_train.iloc[start:end]
    y_batch = y_train.iloc[start:end]

    # Pipeline preprocessing
    X_transformed = pipeline.named_steps[
        'preprocessor'
    ].transform(X_batch)

    # Pipeline feature weighting
    X_transformed = pipeline.named_steps[
        'feature_weighter'
    ].transform(X_transformed)

    # Sample weights for class imbalance
    sample_weights = y_batch.map(class_weights).to_numpy()

    # Incremental training
    pipeline.named_steps['classifier'].partial_fit(
        X_transformed,
        y_batch,
        classes=classes,
        sample_weight=sample_weights
    )

    print(f"Completed: {start:,} → {end:,}")

    del X_batch, y_batch, X_transformed, sample_weights
    gc.collect()


print("Pipeline training completed successfully!")

Completed: 0 → 30,000
Completed: 30,000 → 60,000
Completed: 60,000 → 90,000
Completed: 90,000 → 120,000
Completed: 120,000 → 150,000
Completed: 150,000 → 180,000
Completed: 180,000 → 210,000
Completed: 210,000 → 240,000
Completed: 240,000 → 270,000
Completed: 270,000 → 300,000
Completed: 300,000 → 330,000
Completed: 330,000 → 360,000
Completed: 360,000 → 390,000
Completed: 390,000 → 420,000
Completed: 420,000 → 450,000
Completed: 450,000 → 480,000
Completed: 480,000 → 510,000
Completed: 510,000 → 540,000
Completed: 540,000 → 570,000
Completed: 570,000 → 600,000
Completed: 600,000 → 630,000
Completed: 630,000 → 660,000
Completed: 660,000 → 690,000
Completed: 690,000 → 720,000
Completed: 720,000 → 750,000
Completed: 750,000 → 780,000
Completed: 780,000 → 810,000
Completed: 810,000 → 840,000
Completed: 840,000 → 870,000
Completed: 870,000 → 900,000
Completed: 900,000 → 930,000
Completed: 930,000 → 960,000
Completed: 960,000 → 990,000
Completed: 990,000 → 1,020,000
Completed: 1,020,000 → 1,050,000
Completed: 1,050,000 → 1,080,000
Completed: 1,080,000 → 1,110,000
Completed: 1,110,000 → 1,140,000
Completed: 1,140,000 → 1,170,000
Completed: 1,170,000 → 1,200,000
Completed: 1,200,000 → 1,230,000
Completed: 1,230,000 → 1,260,000
Completed: 1,260,000 → 1,290,000
Completed: 1,290,000 → 1,320,000
Completed: 1,320,000 → 1,350,000
Completed: 1,350,000 → 1,380,000
Completed: 1,380,000 → 1,410,000
Completed: 1,410,000 → 1,440,000
Completed: 1,440,000 → 1,470,000
Completed: 1,470,000 → 1,500,000
Completed: 1,500,000 → 1,530,000
Completed: 1,530,000 → 1,560,000
Completed: 1,560,000 → 1,590,000
Completed: 1,590,000 → 1,620,000
Completed: 1,620,000 → 1,650,000
Completed: 1,650,000 → 1,680,000
Completed: 1,680,000 → 1,710,000
Completed: 1,710,000 → 1,740,000
Completed: 1,740,000 → 1,770,000
Completed: 1,770,000 → 1,778,193
Pipeline training completed successfully!

In [72]:
X_train.columns

Index(['stars', 'reviews', 'price', 'boughtInLastMonth', 'categoryName'], dtype='object')

In [73]:

# Example: a new product
new_product = pd.DataFrame([{
    'categoryName': 'Electronics',
    'stars': 4.5,
    'reviews': 1250,
    'price': 799.99,
    'boughtInLastMonth': 500
}])

# Predict class
prediction = pipeline.predict(new_product)

# Predict probability
probabilities = pipeline.predict_proba(new_product)

print("Predicted class:", prediction[0])
print("Class probabilities:", probabilities[0])
print("Probability of class 1:", probabilities[0, 1])

Predicted class: 1
Class probabilities: [0.46411858 0.53588142]
Probability of class 1: 0.5358814188288178

In [74]:

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

# Transform test data automatically through the pipeline
y_pred = pipeline.predict(X_test)

# Predicted probabilities for ROC-AUC
y_prob = pipeline.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nROC-AUC:", roc_auc_score(y_test, y_prob))

Accuracy: 0.9832819329252793

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99    443358
           1       0.06      0.38      0.11      1191

    accuracy                           0.98    444549
   macro avg       0.53      0.68      0.55    444549
weighted avg       1.00      0.98      0.99    444549


Confusion Matrix:
[[436662   6696]
 [   736    455]]

ROC-AUC: 0.8976086902746105

Completed: 0 → 30,000
Completed: 30,000 → 60,000
Completed: 60,000 → 90,000
Completed: 90,000 → 120,000
Completed: 120,000 → 150,000
Completed: 150,000 → 180,000
Completed: 180,000 → 210,000
Completed: 210,000 → 240,000
Completed: 240,000 → 270,000
Completed: 270,000 → 300,000
Completed: 300,000 → 330,000
Completed: 330,000 → 360,000
Completed: 360,000 → 390,000
Completed: 390,000 → 420,000
Completed: 420,000 → 450,000
Completed: 450,000 → 480,000
Completed: 480,000 → 510,000
Completed: 510,000 → 540,000
Completed: 540,000 → 570,000
Completed: 570,000 → 600,000
Completed: 600,000 → 630,000
Completed: 630,000 → 660,000
Completed: 660,000 → 690,000
Completed: 690,000 → 720,000
Completed: 720,000 → 750,000
Completed: 750,000 → 780,000
Completed: 780,000 → 810,000
Completed: 810,000 → 840,000
Completed: 840,000 → 870,000
Completed: 870,000 → 900,000
Completed: 900,000 → 930,000
Completed: 930,000 → 960,000
Completed: 960,000 → 990,000
Completed: 990,000 → 1,020,000
Completed: 1,020,000 → 1,050,000
Completed: 1,050,000 → 1,080,000
Completed: 1,080,000 → 1,110,000
Completed: 1,110,000 → 1,140,000
Completed: 1,140,000 → 1,170,000
Completed: 1,170,000 → 1,200,000
Completed: 1,200,000 → 1,230,000
Completed: 1,230,000 → 1,260,000
Completed: 1,260,000 → 1,290,000
Completed: 1,290,000 → 1,320,000
Completed: 1,320,000 → 1,350,000
Completed: 1,350,000 → 1,380,000
Completed: 1,380,000 → 1,410,000
Completed: 1,410,000 → 1,440,000
Completed: 1,440,000 → 1,470,000
Completed: 1,470,000 → 1,500,000
Completed: 1,500,000 → 1,530,000
Completed: 1,530,000 → 1,560,000
Completed: 1,560,000 → 1,590,000
Completed: 1,590,000 → 1,620,000
Completed: 1,620,000 → 1,650,000
Completed: 1,650,000 → 1,680,000
Completed: 1,680,000 → 1,710,000
Completed: 1,710,000 → 1,740,000
Completed: 1,740,000 → 1,770,000
Completed: 1,770,000 → 1,778,193
Training completed!

In [76]:

# Predict on raw test data
y_pred = pipeline.predict(X_test)

# Probability of class 1
positive_class_index = np.where(
    pipeline.named_steps['classifier'].classes_ == 1
)[0][0]

probabilities = pipeline.predict_proba(X_test)[
    :, positive_class_index
]

# AI score from 0 to 100
ai_scores = np.clip(probabilities * 100, 0, 100)

results = X_test.copy()
results['Actual_Class'] = np.asarray(y_test)
results['Predicted_Class'] = y_pred
results['AI_Score'] = np.round(ai_scores, 2)

print(results.head(20))

# Save scores
results.to_csv('shop_pilot_ai_scores.csv', index=False)

         stars  reviews    price  boughtInLastMonth             categoryName  \
673381     4.5      393   3439.0               1000  Kitchen & Bath Fixtures
1400390    0.0        0   3248.0                  0        Sports & Outdoors
497377     0.0        0   4790.0                  0        Sports & Outdoors
1450230    0.0        0    954.0                  0        Sports & Outdoors
1942230    0.0        0   6299.0                  0        Sports & Outdoors
1714585    4.7     5375   1245.0                200                   Beauty
26         4.5    21614   1273.0                  0           Hi-Fi Speakers
1927589    4.6      198   2038.0                  0        Sports & Outdoors
616046     5.0        6   2110.0                  0     Beer, Wine & Spirits
788611     4.5     1495    572.0                 50   Cushions & Accessories
682516     3.3      249    763.0                  0           Rough Plumbing
824298     0.0        0    483.0                  0    Sports Toys & Outdoor
641763     0.0        0  14978.0                  0                  Flashes
570104     3.3        9   3094.0                  0       Power & Hand Tools
1252733    4.8     1148    892.0               3000   Health & Personal Care
1021084    0.0        0  15344.0                  0     Surveillance Cameras
496898     0.0        0   6243.0                  0        Sports & Outdoors
147844     0.0        0   1324.0                  0        Sports & Outdoors
2077981    0.0        0  33634.0                  0  Media Streaming Devices
221961     4.8       17    407.0                  0    Plants, Seeds & Bulbs

         Actual_Class  Predicted_Class  AI_Score
673381              0                1     99.90
1400390             0                0      0.00
497377              0                0      0.00
1450230             0                0      0.00
1942230             0                0      0.00
1714585             0                0      5.18
26                  0                0     20.34
1927589             0                0      0.21
616046              0                0      8.44
788611              0                0      0.28
682516              0                0      0.00
824298              0                0      0.00
641763              0                0      0.00
570104              0                0      0.00
1252733             0                1    100.00
1021084             0                0      0.00
496898              0                0      0.00
147844              0                0      0.00
2077981             0                0      0.00
221961              0                0      6.70

In [77]:

new_product = pd.DataFrame([{
    'categoryName': 'Electronics',
    'stars': 4.5,
    'reviews': 1250,
    'price': 799.99,
    'boughtInLastMonth': 500
}])

probability = pipeline.predict_proba(new_product)[
    0, positive_class_index
]

ai_score = round(float(probability * 100), 2)

print(f"ShopPilot AI Score: {ai_score}/100")

ShopPilot AI Score: 53.59/100

In [78]:

import numpy as np
import pandas as pd

def calculate_product_score(df):
    result = df.copy()

    # Configurable importance weights; must sum to 1
    score_weights = {
        'rating': 0.35,
        'popularity': 0.30,
        'reviews': 0.20,
        'affordability': 0.15
    }

    # Normalize rating: 0 to 100
    rating_score = (
        result['stars'].clip(0, 5).fillna(0) / 5
    ) * 100

    # Log scaling prevents huge counts from dominating
    popularity_score = (
        np.log1p(result['boughtInLastMonth'].clip(lower=0))
        / np.log1p(
            max(result['boughtInLastMonth'].max(), 1)
        )
    ) * 100

    reviews_score = (
        np.log1p(result['reviews'].clip(lower=0))
        / np.log1p(max(result['reviews'].max(), 1))
    ) * 100

    # Lower price scores higher for affordability.
    # Relative to the products being scored.
    price = result['price'].clip(lower=0)
    max_price = max(price.max(), 1)

    affordability_score = (
        1 - price / max_price
    ) * 100

    result['AI_Score'] = (
        score_weights['rating'] * rating_score
        + score_weights['popularity'] * popularity_score
        + score_weights['reviews'] * reviews_score
        + score_weights['affordability'] * affordability_score
    ).round(2)

    return result


scored_products = calculate_product_score(X_test)

print(
    scored_products.sort_values(
        'AI_Score', ascending=False
    ).head(20)
)

         stars  reviews   price  boughtInLastMonth  \
1557617    4.6    44511  2831.0              50000
1252287    4.7    14689   510.0              20000
2035093    4.7    88894  1338.0               8000
842578     4.6    82080  4242.0               9000
842576     4.6    63342  4608.0              10000
842573     4.6    60656  1606.0              10000
1252311    4.7    37099  1146.0              10000
1252346    4.5   118097  2038.0               9000
205654     4.7    32139  2930.0               9000
1601457    4.8    15645   763.0              10000
1252367    4.7    30745  1655.0               9000
1252331    4.7    23833  2165.0              10000
842579     4.6    70864  2203.0               7000
260635     4.6    30843  1975.0              10000
1252353    4.7    16839  1337.0              10000
1252772    4.6   291273  2547.0               3000
260648     4.6    39751  2103.0               8000
995350     4.5    41491  1018.0              10000
205650     4.8    10018  3184.0               9000
609681     4.7    80328  3425.0               4000

                                categoryName  AI_Score
1557617                              Grocery     92.35
1252287               Health & Personal Care     88.95
2035093               Coffee, Tea & Espresso     88.95
842578                Printers & Accessories     88.45
842576                Printers & Accessories     88.37
842573                Printers & Accessories     88.33
1252311               Health & Personal Care     88.33
1252346               Health & Personal Care     88.28
205654                          Pet Supplies     87.83
1601457                   Power & Hand Tools     87.81
1252367               Health & Personal Care     87.77
1252331               Health & Personal Care     87.70
842579                Printers & Accessories     87.56
260635                             Skin Care     87.37
1252353               Health & Personal Care     87.21
1252772               Health & Personal Care     87.21
260648                             Skin Care     87.11
995350                               Make-up     87.09
205650                          Pet Supplies     86.88
609681   Water Coolers, Filters & Cartridges     86.88

# Final Pipeline of the model

In [87]:

import numpy as np
import pandas as pd
import gc
import joblib

from scipy import sparse

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)


# =====================================================
# 1. CONFIGURATION
# =====================================================

BATCH_SIZE = 30_000
CLASS_WEIGHTS = {0: 1, 1: 50}
PREDICTION_THRESHOLD = 0.50

# Customize feature importance for the ML classifier
FEATURE_WEIGHTS = {
    'stars': 6.0,
    'reviews': 4.5,
    'price': 1.0,
    'boughtInLastMonth': 7.0,
    'categoryName': 1.0
}

# Customize weights for the independent product score
PRODUCT_SCORE_WEIGHTS = {
    'rating': 0.4,
    'popularity': 0.5,
    'reviews': 0.45,
    'affordability': 0.15
}

# Fixed reference values for consistent scores across batches.
# Adjust these to fit the scale and units of your dataset.
POPULARITY_REFERENCE = 5000
REVIEWS_REFERENCE = 10000
PRICE_REFERENCE = 50000


# =====================================================
# 2. PREPROCESSING
# =====================================================

preprocessor = ColumnTransformer(
    transformers=[
        (
            'OneHotEncoding',
            OneHotEncoder(
                sparse_output=True,
                handle_unknown='ignore'
            ),
            ['categoryName']
        ),
        (
            'StandardScaling',
            StandardScaler(),
            [
                'stars',
                'reviews',
                'price',
                'boughtInLastMonth'
            ]
        )
    ]
)

# Fit on the complete training data so the encoder
# learns all categories present in the training set.
preprocessor.fit(X_train)

print("Preprocessor fitted successfully")


# =====================================================
# 3. FEATURE WEIGHTING TRANSFORMER
# =====================================================

feature_names = preprocessor.get_feature_names_out()
feature_multipliers = np.ones(len(feature_names))

for i, name in enumerate(feature_names):
    for feature, weight in FEATURE_WEIGHTS.items():
        if feature in name:
            feature_multipliers[i] = weight


class FeatureWeighter(BaseEstimator, TransformerMixin):

    def __init__(self, weights):
        self.weights = weights

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        if sparse.issparse(X):
            return X.multiply(self.weights).tocsr()

        return X * self.weights


feature_weighter = FeatureWeighter(feature_multipliers)


# =====================================================
# 4. CLASSIFIER
# =====================================================

classifier = SGDClassifier(
    loss='log_loss',
    alpha=0.0001,
    max_iter=1000,
    tol=1e-3,
    random_state=42,
    class_weight=CLASS_WEIGHTS
)


# =====================================================
# 5. COMPLETE ML PIPELINE
# =====================================================

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('feature_weighter', feature_weighter),
    ('classifier', classifier)
])


# =====================================================
# 6. INCREMENTAL BATCH TRAINING
# =====================================================

classes = np.unique(y_train)

for start in range(0, len(X_train), BATCH_SIZE):

    end = min(start + BATCH_SIZE, len(X_train))

    X_batch = X_train.iloc[start:end]
    y_batch = y_train.iloc[start:end]

    # Transform raw data
    X_transformed = pipeline.named_steps[
        'preprocessor'
    ].transform(X_batch)

    # Apply user-defined feature multipliers
    X_transformed = pipeline.named_steps[
        'feature_weighter'
    ].transform(X_transformed)

    # Class weights are applied inside SGDClassifier
    pipeline.named_steps['classifier'].partial_fit(
        X_transformed,
        y_batch,
        classes=classes
    )

    print(f"Trained: {start:,} -> {end:,}")

    del X_batch, y_batch, X_transformed
    gc.collect()

print("ML pipeline training completed")


# =====================================================
# 7. PRODUCT SCORE CALCULATOR
# =====================================================

def calculate_product_score(df):

    result = df.copy()

    stars = pd.to_numeric(
        result['stars'], errors='coerce'
    ).fillna(0).clip(0, 5)

    reviews = pd.to_numeric(
        result['reviews'], errors='coerce'
    ).fillna(0).clip(lower=0)

    purchases = pd.to_numeric(
        result['boughtInLastMonth'], errors='coerce'
    ).fillna(0).clip(lower=0)

    price = pd.to_numeric(
        result['price'], errors='coerce'
    ).fillna(PRICE_REFERENCE).clip(lower=0)

    # Rating score: 0-100
    rating_score = stars / 5 * 100

    # Log scaling limits domination by extremely high counts
    popularity_score = (
        np.log1p(purchases)
        / np.log1p(POPULARITY_REFERENCE)
        * 100
    ).clip(0, 100)

    review_score = (
        np.log1p(reviews)
        / np.log1p(REVIEWS_REFERENCE)
        * 100
    ).clip(0, 100)

    # Affordability: lower price receives a higher score.
    # This assumes cheaper products are preferable.
    affordability_score = (
        1 - price / PRICE_REFERENCE
    ).clip(0, 1) * 100

    # Combine your chosen weights
    result['AI_Product_Score'] = (
        PRODUCT_SCORE_WEIGHTS['rating'] * rating_score
        + PRODUCT_SCORE_WEIGHTS['popularity'] * popularity_score
        + PRODUCT_SCORE_WEIGHTS['reviews'] * review_score
        + PRODUCT_SCORE_WEIGHTS['affordability']
        * affordability_score
    ).round(2)

    return result


# =====================================================
# 8. PREDICTION FUNCTION
# =====================================================

def predict_products(raw_products):

    # Raw products go directly into the ML pipeline
    probabilities = pipeline.predict_proba(raw_products)

    positive_index = np.where(
        pipeline.named_steps['classifier'].classes_ == 1
    )[0][0]

    # Model-estimated probability of bestseller class
    bestseller_probability = probabilities[:, positive_index]

    # Separate heuristic product-quality score
    results = calculate_product_score(raw_products)

    results['Bestseller_Probability'] = (
        bestseller_probability * 100
    ).round(2)

    results['Predicted_Bestseller'] = (
        bestseller_probability >= PREDICTION_THRESHOLD
    ).astype(int)

    return results


# =====================================================
# 9. EVALUATE ON HELD-OUT TEST DATA
# =====================================================

test_results = predict_products(X_test)

y_pred = test_results['Predicted_Bestseller'].to_numpy()
y_prob = (
    test_results['Bestseller_Probability'].to_numpy() / 100
)

print("\nAccuracy:",
      accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(
    y_test, y_pred, zero_division=0
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nROC-AUC:",
      roc_auc_score(y_test, y_prob))

print("\nAverage Precision:",
      average_precision_score(y_test, y_prob))


# =====================================================
# 10. SAVE THE RESULTS AND MODEL
# =====================================================

test_results.to_csv(
    'shop_pilot_scored_products.csv',
    index=False
)

joblib.dump(
    {
        'pipeline': pipeline,
        'product_score_weights': PRODUCT_SCORE_WEIGHTS,
        'prediction_threshold': PREDICTION_THRESHOLD,
        'popularity_reference': POPULARITY_REFERENCE,
        'reviews_reference': REVIEWS_REFERENCE,
        'price_reference': PRICE_REFERENCE
    },
    'shop_pilot_ai_pipeline.joblib'
)

print("\nSaved product scores and trained pipeline")

Preprocessor fitted successfully
Trained: 0 -> 30,000
Trained: 30,000 -> 60,000
Trained: 60,000 -> 90,000
Trained: 90,000 -> 120,000
Trained: 120,000 -> 150,000
Trained: 150,000 -> 180,000
Trained: 180,000 -> 210,000
Trained: 210,000 -> 240,000
Trained: 240,000 -> 270,000
Trained: 270,000 -> 300,000
Trained: 300,000 -> 330,000
Trained: 330,000 -> 360,000
Trained: 360,000 -> 390,000
Trained: 390,000 -> 420,000
Trained: 420,000 -> 450,000
Trained: 450,000 -> 480,000
Trained: 480,000 -> 510,000
Trained: 510,000 -> 540,000
Trained: 540,000 -> 570,000
Trained: 570,000 -> 600,000
Trained: 600,000 -> 630,000
Trained: 630,000 -> 660,000
Trained: 660,000 -> 690,000
Trained: 690,000 -> 720,000
Trained: 720,000 -> 750,000
Trained: 750,000 -> 780,000
Trained: 780,000 -> 810,000
Trained: 810,000 -> 840,000
Trained: 840,000 -> 870,000
Trained: 870,000 -> 900,000
Trained: 900,000 -> 930,000
Trained: 930,000 -> 960,000
Trained: 960,000 -> 990,000
Trained: 990,000 -> 1,020,000
Trained: 1,020,000 -> 1,050,000
Trained: 1,050,000 -> 1,080,000
Trained: 1,080,000 -> 1,110,000
Trained: 1,110,000 -> 1,140,000
Trained: 1,140,000 -> 1,170,000
Trained: 1,170,000 -> 1,200,000
Trained: 1,200,000 -> 1,230,000
Trained: 1,230,000 -> 1,260,000
Trained: 1,260,000 -> 1,290,000
Trained: 1,290,000 -> 1,320,000
Trained: 1,320,000 -> 1,350,000
Trained: 1,350,000 -> 1,380,000
Trained: 1,380,000 -> 1,410,000
Trained: 1,410,000 -> 1,440,000
Trained: 1,440,000 -> 1,470,000
Trained: 1,470,000 -> 1,500,000
Trained: 1,500,000 -> 1,530,000
Trained: 1,530,000 -> 1,560,000
Trained: 1,560,000 -> 1,590,000
Trained: 1,590,000 -> 1,620,000
Trained: 1,620,000 -> 1,650,000
Trained: 1,650,000 -> 1,680,000
Trained: 1,680,000 -> 1,710,000
Trained: 1,710,000 -> 1,740,000
Trained: 1,740,000 -> 1,770,000
Trained: 1,770,000 -> 1,778,193
ML pipeline training completed

Accuracy: 0.9729276187776825

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.97      0.99    443358
           1       0.05      0.52      0.09      1191

    accuracy                           0.97    444549
   macro avg       0.53      0.75      0.54    444549
weighted avg       1.00      0.97      0.98    444549


Confusion Matrix:
[[431890  11468]
 [   567    624]]

ROC-AUC: 0.7673816269816149

Average Precision: 0.03148578582605149

Saved product scores and trained pipeline

In [89]:
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    average_precision_score,
    confusion_matrix
)
positive_index = np.where(
    pipeline.named_steps['classifier'].classes_ == 1
)[0][0]

y_prob = pipeline.predict_proba(X_test)[:, positive_index]

# Compare different decision thresholds
rows = []

for threshold in [0.50, 0.60, 0.70, 0.80, 0.90, 0.95, 0.99]:
    y_pred_threshold = (y_prob >= threshold).astype(int)

    rows.append({
        'Threshold': threshold,
        'Precision': precision_score(
            y_test, y_pred_threshold, zero_division=0
        ),
        'Recall': recall_score(
            y_test, y_pred_threshold, zero_division=0
        ),
        'F1': f1_score(
            y_test, y_pred_threshold, zero_division=0
        ),
        'Predicted_Bestsellers': int(y_pred_threshold.sum())
    })

print(pd.DataFrame(rows).round(4).to_string(index=False))

print(
    "\nAverage Precision:",
    round(average_precision_score(y_test, y_prob), 4)
)

 Threshold  Precision  Recall     F1  Predicted_Bestsellers
      0.50     0.0516  0.5239 0.0940                  12092
      0.60     0.0519  0.5231 0.0944                  12010
      0.70     0.0521  0.5231 0.0948                  11951
      0.80     0.0526  0.5223 0.0955                  11834
      0.90     0.0531  0.5223 0.0965                  11704
      0.95     0.0535  0.5206 0.0970                  11593
      0.99     0.0542  0.5172 0.0981                  11372

Average Precision: 0.0327

In [91]:
model = joblib.load("shop_pilot_ai_pipeline.joblib")

print("ShopPilot AI model loaded successfully!")

ShopPilot AI model loaded successfully!

In [93]:
import joblib

saved_object = joblib.load("shop_pilot_ai_pipeline.joblib")

print("Object type:", type(saved_object))
print("Keys:", saved_object.keys())

for key, value in saved_object.items():
    print(f"{key}: {type(value)}")

Object type: <class 'dict'>
Keys: dict_keys(['pipeline', 'product_score_weights', 'prediction_threshold', 'popularity_reference', 'reviews_reference', 'price_reference'])
pipeline: <class 'sklearn.pipeline.Pipeline'>
product_score_weights: <class 'dict'>
prediction_threshold: <class 'float'>
popularity_reference: <class 'int'>
reviews_reference: <class 'int'>
price_reference: <class 'int'>

In [94]:
saved = joblib.load("shop_pilot_ai_pipeline.joblib")

model = saved["pipeline"]
PRODUCT_SCORE_WEIGHTS = saved["product_score_weights"]
PREDICTION_THRESHOLD = saved["prediction_threshold"]
POPULARITY_REFERENCE = saved["popularity_reference"]
REVIEWS_REFERENCE = saved["reviews_reference"]
PRICE_REFERENCE = saved["price_reference"]

print("ShopPilot AI loaded successfully!")
print("Prediction threshold:", PREDICTION_THRESHOLD)
print("Product score weights:", PRODUCT_SCORE_WEIGHTS)

ShopPilot AI loaded successfully!
Prediction threshold: 0.5
Product score weights: {'rating': 0.4, 'popularity': 0.5, 'reviews': 0.45, 'affordability': 0.15}

In [95]:
new_products = pd.DataFrame([
    {
        "categoryName": "Electronics",
        "stars": 4.5,
        "reviews": 2500,
        "price": 45000,
        "boughtInLastMonth": 1200
    },
    {
        "categoryName": "Home & Kitchen",
        "stars": 3.8,
        "reviews": 150,
        "price": 1200,
        "boughtInLastMonth": 80
    }
])

# Get the model's predicted probabilities
probabilities = model.predict_proba(new_products)

# Identify the probability column for bestseller = 1
positive_index = list(model.classes_).index(1)
bestseller_probability = probabilities[:, positive_index]

# Apply the threshold saved with your model
predictions = (bestseller_probability >= PREDICTION_THRESHOLD).astype(int)

results = new_products.copy()
results["Bestseller_Probability_Percent"] = (
    bestseller_probability * 100
).round(2)

results["Predicted_Bestseller"] = np.where(
    predictions == 1,
    "Bestseller",
    "Not Bestseller"
)

print(results.to_string(index=False))

  categoryName  stars  reviews  price  boughtInLastMonth  Bestseller_Probability_Percent Predicted_Bestseller
   Electronics    4.5     2500  45000               1200                           100.0           Bestseller
Home & Kitchen    3.8      150   1200                 80                             0.0       Not Bestseller

In [96]:
def calculate_product_score(df):
    rating_score = (df["stars"] / 5 * 100).clip(0, 100)

    popularity_score = (
        np.log1p(df["boughtInLastMonth"])
        / np.log1p(POPULARITY_REFERENCE) * 100
    ).clip(0, 100)

    review_score = (
        np.log1p(df["reviews"])
        / np.log1p(REVIEWS_REFERENCE) * 100
    ).clip(0, 100)

    affordability_score = (
        1 - df["price"] / PRICE_REFERENCE
    ).clip(0, 1) * 100

    scores = {
        "stars": rating_score,
        "boughtInLastMonth": popularity_score,
        "reviews": review_score,
        "price": affordability_score
    }

    total_weight = sum(PRODUCT_SCORE_WEIGHTS.values())

    weighted_score = sum(
        scores[feature] * weight
        for feature, weight in PRODUCT_SCORE_WEIGHTS.items()
        if feature in scores
    )

    used_weight = sum(
        weight
        for feature, weight in PRODUCT_SCORE_WEIGHTS.items()
        if feature in scores
    )

    return (weighted_score / used_weight).round(2)


results["AI_Product_Score"] = calculate_product_score(new_products)

print(results.to_string(index=False))

  categoryName  stars  reviews  price  boughtInLastMonth  Bestseller_Probability_Percent Predicted_Bestseller  AI_Product_Score
   Electronics    4.5     2500  45000               1200                           100.0           Bestseller             84.95
Home & Kitchen    3.8      150   1200                 80                             0.0       Not Bestseller             54.47

In [97]:
feature_cols = [
    "categoryName",
    "stars",
    "reviews",
    "price",
    "boughtInLastMonth"
]

X = df[feature_cols]
y = df["isBestSeller"]

# Convert boolean labels to 0/1 if necessary
if y.dtype == bool:
    y = y.astype(int)

y = y.astype(int).to_numpy()

# 3. Generate predictions in batches
batch_size = 50_000
all_probabilities = []

for start in range(0, len(X), batch_size):
    batch = X.iloc[start:start + batch_size]

    probabilities = model.predict_proba(batch)
    positive_index = list(model.classes_).index(1)

    all_probabilities.append(probabilities[:, positive_index])

    if (start // batch_size) % 5 == 0:
        print(f"Processed {min(start + batch_size, len(X)):,} / {len(X):,}")

# Combine probabilities
y_prob = np.concatenate(all_probabilities)

# Apply the threshold saved with your model
y_pred = (y_prob >= threshold).astype(int)

# 4. Evaluate the complete dataset
print("\n========== SHOPPILOT AI: FULL DATA EVALUATION ==========")
print("Total products:", f"{len(X):,}")
print("Actual bestsellers:", f"{y.sum():,}")
print("Predicted bestsellers:", f"{y_pred.sum():,}")
print("Saved decision threshold:", threshold)

print("\nAccuracy :", round(accuracy_score(y, y_pred), 4))
print("Precision:", round(precision_score(y, y_pred, zero_division=0), 4))
print("Recall   :", round(recall_score(y, y_pred, zero_division=0), 4))
print("F1-score :", round(f1_score(y, y_pred, zero_division=0), 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y, y_pred))

print("\nClassification Report:")
print(classification_report(
    y, y_pred,
    target_names=["Not Bestseller", "Bestseller"],
    zero_division=0
))

print("ROC-AUC:", round(roc_auc_score(y, y_prob), 4))
print("Average Precision:", round(average_precision_score(y, y_prob), 4))

Processed 50,000 / 2,222,742
Processed 300,000 / 2,222,742
Processed 550,000 / 2,222,742
Processed 800,000 / 2,222,742
Processed 1,050,000 / 2,222,742
Processed 1,300,000 / 2,222,742
Processed 1,550,000 / 2,222,742
Processed 1,800,000 / 2,222,742
Processed 2,050,000 / 2,222,742

========== SHOPPILOT AI: FULL DATA EVALUATION ==========
Total products: 2,222,742
Actual bestsellers: 6,018
Predicted bestsellers: 56,806
Saved decision threshold: 0.99

Accuracy : 0.9745
Precision: 0.0545
Recall   : 0.5143
F1-score : 0.0985

Confusion Matrix:
[[2163013   53711]
 [   2923    3095]]

Classification Report:
                precision    recall  f1-score   support

Not Bestseller       1.00      0.98      0.99   2216724
    Bestseller       0.05      0.51      0.10      6018

      accuracy                           0.97   2222742
     macro avg       0.53      0.75      0.54   2222742
  weighted avg       1.00      0.97      0.98   2222742

ROC-AUC: 0.711
Average Precision: 0.034

In [98]:
full_results = df.copy()

full_results["Bestseller_Probability_Percent"] = (
    y_prob * 100
).round(2)

full_results["Predicted_Bestseller"] = y_pred

full_results["Prediction_Label"] = np.where(
    y_pred == 1,
    "Bestseller",
    "Not Bestseller"
)

full_results.to_csv(
    "shop_pilot_ai_full_predictions.csv",
    index=False
)

print("Saved shop_pilot_ai_full_predictions.csv")

Saved shop_pilot_ai_full_predictions.csv

In [100]:
import joblib
import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    average_precision_score
)

# ============================================================
# 1. LOAD SAVED SHOPPILOT AI MODEL
# ============================================================

saved = joblib.load("shop_pilot_ai_pipeline.joblib")

model = saved["pipeline"]
PRODUCT_SCORE_WEIGHTS = saved["product_score_weights"]
PREDICTION_THRESHOLD = saved["prediction_threshold"]

POPULARITY_REFERENCE = saved["popularity_reference"]
REVIEWS_REFERENCE = saved["reviews_reference"]
PRICE_REFERENCE = saved["price_reference"]

print("ShopPilot AI loaded successfully!")
print("Prediction threshold:", PREDICTION_THRESHOLD)
print("Product score weights:", PRODUCT_SCORE_WEIGHTS)


# ============================================================
# 2. PREPARE FULL DATASET
# ============================================================

# Replace df with the variable containing your full dataset.
feature_cols = [
    "categoryName",
    "stars",
    "reviews",
    "price",
    "boughtInLastMonth"
]

X = df[feature_cols].copy()

# Keep original labels for evaluation, if available.
has_labels = "isBestSeller" in df.columns

if has_labels:
    y = df["isBestSeller"].astype(int).to_numpy()


# ============================================================
# 3. CALCULATE AI PRODUCT SCORE (0-100)
# ============================================================

def calculate_ai_product_score(products):
    products = products.copy()

    # Handle missing or invalid numerical values safely.
    stars = pd.to_numeric(products["stars"], errors="coerce").fillna(0).clip(0, 5)
    reviews = pd.to_numeric(products["reviews"], errors="coerce").fillna(0).clip(lower=0)
    price = pd.to_numeric(products["price"], errors="coerce").fillna(PRICE_REFERENCE).clip(lower=0)
    bought = pd.to_numeric(
        products["boughtInLastMonth"], errors="coerce"
    ).fillna(0).clip(lower=0)

    rating_score = stars / 5 * 100

    popularity_score = (
        np.log1p(bought) / np.log1p(POPULARITY_REFERENCE) * 100
    ).clip(0, 100)

    review_score = (
        np.log1p(reviews) / np.log1p(REVIEWS_REFERENCE) * 100
    ).clip(0, 100)

    affordability_score = (
        1 - price / PRICE_REFERENCE
    ).clip(0, 1) * 100

    component_scores = {
        "stars": rating_score,
        "boughtInLastMonth": popularity_score,
        "reviews": review_score,
        "price": affordability_score
    }

    total_weight = sum(
        PRODUCT_SCORE_WEIGHTS.get(feature, 0)
        for feature in component_scores
    )

    if total_weight <= 0:
        raise ValueError("No valid product-score weights found.")

    score = sum(
        component_scores[feature] * PRODUCT_SCORE_WEIGHTS.get(feature, 0)
        for feature in component_scores
    ) / total_weight

    # Round and cap strictly below 100.
    score = np.asarray(score, dtype=float)
    score = np.nan_to_num(score, nan=0.0, posinf=99.99, neginf=0.0)
    score = np.clip(score, 0, 99.99)

    return np.round(score, 2)


# ============================================================
# 4. PREDICT THE FULL DATASET IN BATCHES
# ============================================================

batch_size = 50_000
probability_batches = []

positive_index = list(model.classes_).index(1)

for start in range(0, len(X), batch_size):
    batch = X.iloc[start:start + batch_size]

    batch_probabilities = model.predict_proba(batch)
    probability_batches.append(batch_probabilities[:, positive_index])

    print(f"Processed {min(start + batch_size, len(X)):,} / {len(X):,}")

bestseller_probabilities = np.concatenate(probability_batches)

predicted_labels = (
    bestseller_probabilities >= PREDICTION_THRESHOLD
).astype(int)


# ============================================================
# 5. BUILD FULL RESULTS
# ============================================================

results = df.copy()

results["Bestseller_Probability_Percent"] = np.round(
    bestseller_probabilities * 100, 2
)

results["Predicted_Bestseller"] = predicted_labels

results["Prediction_Label"] = np.where(
    predicted_labels == 1,
    "Bestseller",
    "Not Bestseller"
)

results["AI_Product_Score"] = calculate_ai_product_score(X)

# Ensure the displayed score remains strictly below 100.
results["AI_Product_Score"] = results["AI_Product_Score"].clip(upper=99.99)


# ============================================================
# 6. EVALUATE IF ACTUAL LABELS EXIST
# ============================================================

if has_labels:
    print("\n========== FULL DATA EVALUATION ==========")
    print("Total products:", f"{len(X):,}")
    print("Actual bestsellers:", f"{y.sum():,}")
    print("Predicted bestsellers:", f"{predicted_labels.sum():,}")

    print("\nAccuracy :", round(accuracy_score(y, predicted_labels), 4))
    print("Precision:", round(precision_score(y, predicted_labels, zero_division=0), 4))
    print("Recall   :", round(recall_score(y, predicted_labels, zero_division=0), 4))
    print("F1-score :", round(f1_score(y, predicted_labels, zero_division=0), 4))

    print("\nConfusion Matrix:")
    print(confusion_matrix(y, predicted_labels))

    print("\nClassification Report:")
    print(classification_report(
        y,
        predicted_labels,
        target_names=["Not Bestseller", "Bestseller"],
        zero_division=0
    ))

    print("ROC-AUC:", round(roc_auc_score(y, bestseller_probabilities), 4))
    print("Average Precision:", round(
        average_precision_score(y, bestseller_probabilities), 4
    ))


# ============================================================
# 7. DISPLAY RANDOM PRODUCTS
# ============================================================

sample_size = min(20, len(results))

random_products = results.sample(
    n=sample_size,
    random_state=None
)

display_cols = [
    "categoryName",
    "stars",
    "reviews",
    "price",
    "boughtInLastMonth",
    "AI_Product_Score",
    "Bestseller_Probability_Percent",
    "Prediction_Label"
]

if has_labels:
    display_cols.insert(1, "isBestSeller")

print("\n========== RANDOM SHOPPILOT AI PRODUCTS ==========")

display(
    random_products[display_cols]
    .sort_values("AI_Product_Score", ascending=False)
    .reset_index(drop=True)
)


# ============================================================
# 8. SAVE ALL PREDICTIONS
# ============================================================

results.to_csv("Predictions.csv", index=False)

print("\nSaved: shop_pilot_ai_full_predictions.csv")
print("Total products scored:", f"{len(results):,}")

ShopPilot AI loaded successfully!
Prediction threshold: 0.5
Product score weights: {'rating': 0.4, 'popularity': 0.5, 'reviews': 0.45, 'affordability': 0.15}
Processed 50,000 / 2,222,742
Processed 100,000 / 2,222,742
Processed 150,000 / 2,222,742
Processed 200,000 / 2,222,742
Processed 250,000 / 2,222,742
Processed 300,000 / 2,222,742
Processed 350,000 / 2,222,742
Processed 400,000 / 2,222,742
Processed 450,000 / 2,222,742
Processed 500,000 / 2,222,742
Processed 550,000 / 2,222,742
Processed 600,000 / 2,222,742
Processed 650,000 / 2,222,742
Processed 700,000 / 2,222,742
Processed 750,000 / 2,222,742
Processed 800,000 / 2,222,742
Processed 850,000 / 2,222,742
Processed 900,000 / 2,222,742
Processed 950,000 / 2,222,742
Processed 1,000,000 / 2,222,742
Processed 1,050,000 / 2,222,742
Processed 1,100,000 / 2,222,742
Processed 1,150,000 / 2,222,742
Processed 1,200,000 / 2,222,742
Processed 1,250,000 / 2,222,742
Processed 1,300,000 / 2,222,742
Processed 1,350,000 / 2,222,742
Processed 1,400,000 / 2,222,742
Processed 1,450,000 / 2,222,742
Processed 1,500,000 / 2,222,742
Processed 1,550,000 / 2,222,742
Processed 1,600,000 / 2,222,742
Processed 1,650,000 / 2,222,742
Processed 1,700,000 / 2,222,742
Processed 1,750,000 / 2,222,742
Processed 1,800,000 / 2,222,742
Processed 1,850,000 / 2,222,742
Processed 1,900,000 / 2,222,742
Processed 1,950,000 / 2,222,742
Processed 2,000,000 / 2,222,742
Processed 2,050,000 / 2,222,742
Processed 2,100,000 / 2,222,742
Processed 2,150,000 / 2,222,742
Processed 2,200,000 / 2,222,742
Processed 2,222,742 / 2,222,742

========== FULL DATA EVALUATION ==========
Total products: 2,222,742
Actual bestsellers: 6,018
Predicted bestsellers: 60,488

Accuracy : 0.9729
Precision: 0.0523
Recall   : 0.5261
F1-score : 0.0952

Confusion Matrix:
[[2159402   57322]
 [   2852    3166]]

Classification Report:
                precision    recall  f1-score   support

Not Bestseller       1.00      0.97      0.99   2216724
    Bestseller       0.05      0.53      0.10      6018

      accuracy                           0.97   2222742
     macro avg       0.53      0.75      0.54   2222742
  weighted avg       1.00      0.97      0.98   2222742

ROC-AUC: 0.711
Average Precision: 0.034

========== RANDOM SHOPPILOT AI PRODUCTS ==========

,categoryName,isBestSeller,stars,reviews,price,boughtInLastMonth,AI_Product_Score,Bestseller_Probability_Percent,Prediction_Label
0,"Home Cinema, TV & Video",0,4.6,2634,2420.0,0,85.52,0.0,Not Bestseller
1,Hair Care,0,4.5,2576,1179.0,0,85.28,0.0,Not Bestseller
2,Hardware,0,4.4,365,2038.0,0,64.09,0.0,Not Bestseller
3,Bath & Body,0,4.5,241,915.0,0,59.59,0.0,Not Bestseller
4,Hobbies,0,4.8,100,2610.0,0,50.11,0.0,Not Bestseller
5,Car & Vehicle Electronics,0,3.9,41,928.0,0,40.58,0.0,Not Bestseller
6,Sports & Outdoors,0,4.8,5,5861.0,0,19.45,0.0,Not Bestseller
7,Sports & Outdoors,0,3.6,4,4967.0,0,17.47,0.0,Not Bestseller
8,Networking Devices,0,5.0,1,12771.0,0,7.53,0.0,Not Bestseller
9,Microphones,0,0.0,0,1553.0,0,0.00,0.0,Not Bestseller
10,Computer Audio & Video Accessories,0,0.0,0,13762.0,0,0.00,0.0,Not Bestseller
11,Sports & Outdoors,0,0.0,0,74545.0,0,0.00,0.0,Not Bestseller
12,Sports & Outdoors,0,0.0,0,1655.0,0,0.00,0.0,Not Bestseller
13,Sports & Outdoors,0,0.0,0,66893.0,0,0.00,0.0,Not Bestseller
14,Sports & Outdoors,0,0.0,0,8156.0,0,0.00,0.0,Not Bestseller
15,Sports & Outdoors,0,0.0,0,1974.0,0,0.00,0.0,Not Bestseller
16,Sports & Outdoors,0,0.0,0,30925.0,0,0.00,0.0,Not Bestseller
17,Sports & Outdoors,0,0.0,0,394.0,0,0.00,0.0,Not Bestseller
18,Sports & Outdoors,0,0.0,0,54039.0,0,0.00,0.0,Not Bestseller
19,Sports & Outdoors,0,0.0,0,1133.0,0,0.00,0.0,Not Bestseller

Saved: shop_pilot_ai_full_predictions.csv
Total products scored: 2,222,742