In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/asaniczka/amazon-uk-products-dataset-2023/amz_uk_processed_data.csv

In [2]:
df = pd.read_csv('/kaggle/input/datasets/asaniczka/amazon-uk-products-dataset-2023/amz_uk_processed_data.csv')

In [3]:
df.head()

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
0,B09B96TG33,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/71C3lbbeLs...,https://www.amazon.co.uk/dp/B09B96TG33,4.7,15308,21.99,False,0,Hi-Fi Speakers
1,B01HTH3C8S,"Anker Soundcore mini, Super-Portable Bluetooth...",https://m.media-amazon.com/images/I/61c5rSxwP0...,https://www.amazon.co.uk/dp/B01HTH3C8S,4.7,98099,23.99,True,0,Hi-Fi Speakers
2,B09B8YWXDF,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/61j3SEUjMJ...,https://www.amazon.co.uk/dp/B09B8YWXDF,4.7,15308,21.99,False,0,Hi-Fi Speakers
3,B09B8T5VGV,"Echo Dot with clock (5th generation, 2022 rele...",https://m.media-amazon.com/images/I/71yf6yTNWS...,https://www.amazon.co.uk/dp/B09B8T5VGV,4.7,7205,31.99,False,0,Hi-Fi Speakers
4,B09WX6QD65,Introducing Echo Pop | Full sound compact Wi-F...,https://m.media-amazon.com/images/I/613dEoF9-r...,https://www.amazon.co.uk/dp/B09WX6QD65,4.6,1881,17.99,False,0,Hi-Fi Speakers

In [4]:
df.shape

(2222742, 10)

In [5]:
df.tail()

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
2222737,B0CHSD7P2Q,"Motorbike Armour, Motorbike Clothing, Cycling ...",https://m.media-amazon.com/images/I/61ycPU7k4k...,https://www.amazon.co.uk/dp/B0CHSD7P2Q,0.0,0,22.34,False,0,Motorbike Clothing
2222738,B0B7B8FNBQ,PROFIRST Waterproof Motorcycle 2 Piece Ladies ...,https://m.media-amazon.com/images/I/51gkh0iYT5...,https://www.amazon.co.uk/dp/B0B7B8FNBQ,0.0,0,97.99,False,0,Motorbike Clothing
2222739,B0BD5FL5FB,Men’s Motorcycle Motorbike Biker Trousers Kevl...,https://m.media-amazon.com/images/I/81gJgaMHg4...,https://www.amazon.co.uk/dp/B0BD5FL5FB,0.0,0,52.99,False,0,Motorbike Clothing
2222740,B008OYLL4I,Texpeed Mens Motorcycle Motorbike Biker Trouse...,https://m.media-amazon.com/images/I/81KQ5askGG...,https://www.amazon.co.uk/dp/B008OYLL4I,4.3,404,79.99,False,0,Motorbike Clothing
2222741,B08P3W9B3T,RIDEX CJ223 Motorcycle Motorbike Jacket Armour...,https://m.media-amazon.com/images/I/61QaDygK8m...,https://www.amazon.co.uk/dp/B08P3W9B3T,4.5,34,53.99,False,0,Motorbike Clothing

In [6]:
df.sample(2)

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
701163,B0CHFS6MZ9,"Ceolup Glucose Monitoring Watch,Smart Watch wi...",https://m.media-amazon.com/images/I/718TssBg91...,https://www.amazon.co.uk/dp/B0CHFS6MZ9,0.0,0,49.69,False,0,Sports & Outdoors
398192,B0BFJ8NZ2V,Balega Recycled Hidden Comfort Performance No ...,https://m.media-amazon.com/images/I/81dPlZVffv...,https://www.amazon.co.uk/dp/B0BFJ8NZ2V,4.8,36,16.00,False,0,Sports & Outdoors

In [7]:
df.isna().sum()

asin                 0
title                0
imgUrl               0
productURL           0
stars                0
reviews              0
price                0
isBestSeller         0
boughtInLastMonth    0
categoryName         0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2222742 entries, 0 to 2222741
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   asin               object
 1   title              object
 2   imgUrl             object
 3   productURL         object
 4   stars              float64
 5   reviews            int64
 6   price              float64
 7   isBestSeller       bool
 8   boughtInLastMonth  int64
 9   categoryName       object
dtypes: bool(1), float64(2), int64(2), object(5)
memory usage: 154.7+ MB

In [9]:
df.describe()

              stars       reviews         price  boughtInLastMonth
count  2.222742e+06  2.222742e+06  2.222742e+06       2.222742e+06
mean   2.031870e+00  3.821617e+02  9.425737e+01       1.856902e+01
std    2.185497e+00  5.020752e+03  3.606225e+02       1.919030e+02
min    0.000000e+00  0.000000e+00  0.000000e+00       0.000000e+00
25%    0.000000e+00  0.000000e+00  1.000000e+01       0.000000e+00
50%    0.000000e+00  0.000000e+00  1.990000e+01       0.000000e+00
75%    4.400000e+00  4.400000e+01  4.771000e+01       0.000000e+00
max    5.000000e+00  1.356658e+06  1.000000e+05       5.000000e+04

In [10]:
df.corr(numeric_only = True)

,stars,reviews,price,isBestSeller,boughtInLastMonth
stars,1.000000,0.085124,-0.122505,0.056826,0.106259
reviews,0.085124,1.000000,-0.012482,0.061835,0.095229
price,-0.122505,-0.012482,1.000000,-0.010241,-0.021390
isBestSeller,0.056826,0.061835,-0.010241,1.000000,0.222299
boughtInLastMonth,0.106259,0.095229,-0.021390,0.222299,1.000000

In [11]:
df['isBestSeller']

0          False
1           True
2          False
3          False
4          False
           ...
2222737    False
2222738    False
2222739    False
2222740    False
2222741    False
Name: isBestSeller, Length: 2222742, dtype: bool

In [12]:
num_cols = df.select_dtypes(include='number')

In [13]:
cat_cols = df.select_dtypes(exclude = 'number')

In [14]:
num_cols

         stars  reviews  price  boughtInLastMonth
0          4.7    15308  21.99                  0
1          4.7    98099  23.99                  0
2          4.7    15308  21.99                  0
3          4.7     7205  31.99                  0
4          4.6     1881  17.99                  0
...        ...      ...    ...                ...
2222737    0.0        0  22.34                  0
2222738    0.0        0  97.99                  0
2222739    0.0        0  52.99                  0
2222740    4.3      404  79.99                  0
2222741    4.5       34  53.99                  0

[2222742 rows x 4 columns]

In [15]:
cat_cols

,asin,title,imgUrl,productURL,isBestSeller,categoryName
0,B09B96TG33,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/71C3lbbeLs...,https://www.amazon.co.uk/dp/B09B96TG33,False,Hi-Fi Speakers
1,B01HTH3C8S,"Anker Soundcore mini, Super-Portable Bluetooth...",https://m.media-amazon.com/images/I/61c5rSxwP0...,https://www.amazon.co.uk/dp/B01HTH3C8S,True,Hi-Fi Speakers
2,B09B8YWXDF,"Echo Dot (5th generation, 2022 release) | Big ...",https://m.media-amazon.com/images/I/61j3SEUjMJ...,https://www.amazon.co.uk/dp/B09B8YWXDF,False,Hi-Fi Speakers
3,B09B8T5VGV,"Echo Dot with clock (5th generation, 2022 rele...",https://m.media-amazon.com/images/I/71yf6yTNWS...,https://www.amazon.co.uk/dp/B09B8T5VGV,False,Hi-Fi Speakers
4,B09WX6QD65,Introducing Echo Pop | Full sound compact Wi-F...,https://m.media-amazon.com/images/I/613dEoF9-r...,https://www.amazon.co.uk/dp/B09WX6QD65,False,Hi-Fi Speakers
...,...,...,...,...,...,...
2222737,B0CHSD7P2Q,"Motorbike Armour, Motorbike Clothing, Cycling ...",https://m.media-amazon.com/images/I/61ycPU7k4k...,https://www.amazon.co.uk/dp/B0CHSD7P2Q,False,Motorbike Clothing
2222738,B0B7B8FNBQ,PROFIRST Waterproof Motorcycle 2 Piece Ladies ...,https://m.media-amazon.com/images/I/51gkh0iYT5...,https://www.amazon.co.uk/dp/B0B7B8FNBQ,False,Motorbike Clothing
2222739,B0BD5FL5FB,Men’s Motorcycle Motorbike Biker Trousers Kevl...,https://m.media-amazon.com/images/I/81gJgaMHg4...,https://www.amazon.co.uk/dp/B0BD5FL5FB,False,Motorbike Clothing
2222740,B008OYLL4I,Texpeed Mens Motorcycle Motorbike Biker Trouse...,https://m.media-amazon.com/images/I/81KQ5askGG...,https://www.amazon.co.uk/dp/B008OYLL4I,False,Motorbike Clothing
2222741,B08P3W9B3T,RIDEX CJ223 Motorcycle Motorbike Jacket Armour...,https://m.media-amazon.com/images/I/61QaDygK8m...,https://www.amazon.co.uk/dp/B08P3W9B3T,False,Motorbike Clothing

In [16]:
df['imgUrl']

0          https://m.media-amazon.com/images/I/71C3lbbeLs...
1          https://m.media-amazon.com/images/I/61c5rSxwP0...
2          https://m.media-amazon.com/images/I/61j3SEUjMJ...
3          https://m.media-amazon.com/images/I/71yf6yTNWS...
4          https://m.media-amazon.com/images/I/613dEoF9-r...
                                 ...
2222737    https://m.media-amazon.com/images/I/61ycPU7k4k...
2222738    https://m.media-amazon.com/images/I/51gkh0iYT5...
2222739    https://m.media-amazon.com/images/I/81gJgaMHg4...
2222740    https://m.media-amazon.com/images/I/81KQ5askGG...
2222741    https://m.media-amazon.com/images/I/61QaDygK8m...
Name: imgUrl, Length: 2222742, dtype: object

In [17]:
df.shape

(2222742, 10)

In [18]:
df.columns

Index(['asin', 'title', 'imgUrl', 'productURL', 'stars', 'reviews', 'price',
       'isBestSeller', 'boughtInLastMonth', 'categoryName'],
      dtype='object')

In [19]:
num_cols.columns

Index(['stars', 'reviews', 'price', 'boughtInLastMonth'], dtype='object')

In [20]:
cat_cols.columns

Index(['asin', 'title', 'imgUrl', 'productURL', 'isBestSeller',
       'categoryName'],
      dtype='object')

In [21]:
num_cols['price']

0          21.99
1          23.99
2          21.99
3          31.99
4          17.99
           ...
2222737    22.34
2222738    97.99
2222739    52.99
2222740    79.99
2222741    53.99
Name: price, Length: 2222742, dtype: float64

In [22]:
#Converting Pounds Into Rupees
df['price'] = df['price'] * 127.43

In [23]:
df['price']

0           2802.1857
1           3057.0457
2           2802.1857
3           4076.4857
4           2292.4657
              ...
2222737     2846.7862
2222738    12486.8657
2222739     6752.5157
2222740    10193.1257
2222741     6879.9457
Name: price, Length: 2222742, dtype: float64

In [24]:
df['price'] = df['price'].apply(
    lambda x: np.ceil(x) if x % 1 >= 0.5 else np.floor(x)
)

In [25]:
df['price']

0           2802.0
1           3057.0
2           2802.0
3           4076.0
4           2292.0
            ...
2222737     2847.0
2222738    12487.0
2222739     6753.0
2222740    10193.0
2222741     6880.0
Name: price, Length: 2222742, dtype: float64

In [26]:
df['productURL']

0          https://www.amazon.co.uk/dp/B09B96TG33
1          https://www.amazon.co.uk/dp/B01HTH3C8S
2          https://www.amazon.co.uk/dp/B09B8YWXDF
3          https://www.amazon.co.uk/dp/B09B8T5VGV
4          https://www.amazon.co.uk/dp/B09WX6QD65
                            ...
2222737    https://www.amazon.co.uk/dp/B0CHSD7P2Q
2222738    https://www.amazon.co.uk/dp/B0B7B8FNBQ
2222739    https://www.amazon.co.uk/dp/B0BD5FL5FB
2222740    https://www.amazon.co.uk/dp/B008OYLL4I
2222741    https://www.amazon.co.uk/dp/B08P3W9B3T
Name: productURL, Length: 2222742, dtype: object

In [27]:
df.sample(2)

,asin,title,imgUrl,productURL,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
2165686,B086367VCH,Albany Tweed Suede Collar Tailored Jacket,https://m.media-amazon.com/images/I/91MgpgVSF6...,https://www.amazon.co.uk/dp/B086367VCH,3.0,2,9198.0,False,0,Girls
407734,B0BW8SCSCV,LindoMaker Shorts for Women Denim High Waisted...,https://m.media-amazon.com/images/I/61C03E6p-8...,https://www.amazon.co.uk/dp/B0BW8SCSCV,0.0,0,1146.0,False,0,Sports & Outdoors

In [28]:
df['categoryName'].value_counts()

categoryName
Sports & Outdoors                 826076
Skin Care                          18755
Fragrances                         18563
Make-up                            18453
Manicure & Pedicure Products       17212
                                   ...
Torches                               64
Smart Home Security & Lighting        57
Lighting                              50
Smart Speakers                        25
Cameras                               12
Name: count, Length: 296, dtype: int64

In [29]:
df.drop(columns = ['imgUrl','productURL','title'],axis = 1,inplace = True)

In [30]:
df.sample(5)

,asin,stars,reviews,price,isBestSeller,boughtInLastMonth,categoryName
1237963,B002SKCO7W,4.4,331,1209.0,False,0,Outdoor Cooking
329401,B0BMP5546H,4.7,24,5988.0,False,0,Barebone PCs
524530,B09Q3NZZTV,0.0,0,4199.0,False,0,Sports & Outdoors
1368290,B0BCYV2ZHH,0.0,0,790.0,False,0,Sports & Outdoors
76230,B09CYMZ1QM,4.3,41,2673.0,False,0,Boys

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,LabelEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [32]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,roc_curve,roc_auc_score

In [33]:
X = df.drop(columns = ['isBestSeller'],axis = 1)

In [34]:
df['isBestSeller'] = df['isBestSeller'].apply(lambda x: 1 if x else 0)

In [35]:
y = df['isBestSeller']

In [36]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [37]:
X_train.shape

(1778193, 6)

In [38]:
X_test.shape

(444549, 6)

In [39]:
y_train.shape

(1778193,)

In [40]:
y_test.shape

(444549,)

In [41]:
X_train

,asin,stars,reviews,price,boughtInLastMonth,categoryName
757021,B0892SBRL3,4.6,126,28140.0,0,Sports & Outdoors
1953809,B0CGH5VJZT,0.0,0,751.0,0,Sports & Outdoors
1305660,B0CG8CBDK5,0.0,0,2086.0,0,Toy Advent Calendars
1440599,B0CDCF835P,0.0,0,1451.0,0,Sports & Outdoors
1809750,B09Q5V9BL1,5.0,1,858.0,0,Remote & App-Controlled Devices
...,...,...,...,...,...,...
1570006,B09KXV3FP4,4.7,308,12103.0,0,Camera & Photo Accessories
732180,B0BJ8XPL2T,0.0,0,48296.0,0,Sports & Outdoors
110268,B09TWLC3LS,5.0,4,1911.0,0,Handmade Gifts
1692743,B08FXJ1LQ9,0.0,0,28083.0,0,Sports & Outdoors
2219110,B0CGXG9K4M,0.0,0,2306.0,0,Table Tennis

In [42]:
tr1 = ColumnTransformer(transformers=[
    ('OneHotEncoding',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),['asin','categoryName']), 
    ('StandardScaling',StandardScaler(),['stars','reviews','price','boughtInLastMonth'])
])

In [43]:
tr1

ColumnTransformer(transformers=[('OneHotEncoding',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['asin', 'categoryName']),
                                ('StandardScaling', StandardScaler(),
                                 ['stars', 'reviews', 'price',
                                  'boughtInLastMonth'])])

In [44]:
# pipe1 = Pipeline(steps=[
#     ('preprocessing', tr1),
#     ('model', RandomForestClassifier(
#         n_estimators=100,
#         max_depth=15,
#         min_samples_split=10,
#         min_samples_leaf=4,
#         max_features='sqrt',
#         max_leaf_nodes=100,
#         min_impurity_decrease=0.01,
#         bootstrap=True,
#         max_samples=0.8,
#         class_weight='balanced',
#         random_state=42,
#         n_jobs=-1
#     ))
# ])

In [45]:
# pipe1.fit(X_train,y_train)